### ISSUE TITLE
Sequence Number missing during gathered(ios_acls)

### ISSUE THREAD

**Issue by JeromeH27** [ansible-collections/cisco.ios#1041]
##### SUMMARY

Sequence Number missing during gathered(ios_acls)
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios

##### ANSIBLE VERSION

```
ansible 2.10.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Mar 19 2021, 05:13:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

##### COLLECTION VERSION

```paste below
cisco.ios.ios: 6.1.3
```

##### CONFIGURATION

```paste below
Nothing
```

##### STEPS TO REPRODUCE

Executing this task:
 - name: Collect ACL
  cisco.ios.ios_acls:
    config:
    state: gathered

```yaml

Executing this task:
 - name: Collect ACL
  cisco.ios.ios_acls:
    config:
    state: gathered

we got this return without sequence number by aces.
 ...
{'name': 'SNMP-ACCESS', 'acl_type': 'standard', 
   'aces': [
     {'grant': 'permit', 'source': {'host': '10.2.9.1'}}, 
	 {'grant': 'permit', 'source': {'host': '10.18.9.25'}},
	 {'grant': 'permit', 'source': {'host': '10.2.9.44'}},
...

```

##### ACTUAL RESULTS

```paste below

```

**Comment by KB-perByte** [comment]
Hey @JeromeH27, can you please help us with the appliance version and the output of this command `show running-config | section access-list`
For us to understand the issue in a better way.
Regards.

**Comment by JeromeH27** [comment]
Hey KB-perByte,

the appliance version is 15.2(7)E7(switch model WS-C2960X-48TD-L). in fact the sequence number isn't displayed with the command: show running-config | section access-list

here the output I got for the switch:
  #show running-config | section access-list
    ...
    ip access-list standard SNMP-ACCESS
      permit 10.2.9.1
      permit 10.18.9.25
    ...

To get sequence number, on this switch I should use the command: show access-lists
#show access-lists
    ...
    Standard IP access list SNMP-ACCESS
      10 permit 10.2.9.1
      100 permit 10.18.9.25
    ...


On a newer switch(model: C9300-48P, version: 16.12.02), we got the sequence number:
  #show running-config | section access-list
    ...
    ip access-list standard SNMP-ACCESS
      10 permit 10.2.9.1
       100 permit 10.18.9.25
    ...

**Comment by KB-perByte** [comment]
Apologies, the module does not support IOS version 15.x, the latest support for the module/ collection is IOSXE 17.x
Please note, we do not support appliances which has been marked EOL from Cisco. 
Regards.
