### ISSUE TITLE
ios_config force remove lines

### ISSUE THREAD

**Issue by dsglaser** [ansible-collections/cisco.ios#109]
##### SUMMARY
Reopening of https://github.com/ansible/ansible/issues/53862 into the appropriate Cisco collections repo. 
Some ios config lines require existing config to be removed before successful application. An example of this is the 'service-policy input '. You cannot specify a new policy-map name to apply without removing the old one by name first. In this case, the 'before' option isn't enough.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
networking/ios_config

##### ADDITIONAL INFORMATION
The service-policy command is a good example of how this could be useful. Let's say you want a task that will go through and remove any non-standard service-policies bound to interfaces and then add a standard one. There could be a host_vars mapping of service-policy to interface names to loop through in order to achieve this.

Unfortunately, in order to be removed, you need to negate the entire service-policy command, including the name. Since the names are free form, they can vary from interface to interface. At the moment, I think that the only feasible way to accomplish the task described above is by using a nested loop structure wherein you loop through the output of a registered command like "show run {{ item.interface }} | include service-policy" to register the configured service-policies and then compare the output to a loop of your host_vars interface/service-policy mappings. I spent some hours trying to accomplish this but eventually gave up, although it is probably possible.

So anyway, some option for the ios_config module to run the "no" form of whatever it's matching against in the config, regardless of what it looks like, would be nice. The "before" option gets part way there, but it doesn't work when the name of the thing you are removing doesn't necessarily match the name of the thing you're adding.

**Comment by KB-perByte** [comment]
Hi @dsglaser,
The ios_config module is intended to push configuration and not take any decision based on the resource we are dealing with. For that, we have resource modules that are continuously being developed. With the config module that would be adding manual commands to negate the previous configuration or you can request for a feature of service-policy as a [resource module](https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html). Thanks
