### ISSUE TITLE
gather_network_resources: l3_interfaces returns all interfaces on device instead of only interfaces that have an IP address defined

### ISSUE THREAD

**Issue by mpsOxygen** [ansible-collections/cisco.ios#116]
##### SUMMARY

gather_network_resources: l3_interfaces returns all interfaces on device instead of only interfaces that have an IP address defined.
            "l3_interfaces": [
                {
                    "name": "Port-channel1"
                },
                {
                    "ipv4": [
                        {
                            "address": "172.25.1.1 255.255.255.0"
                        }
                    ],
                    "name": "GigabitEthernet0/0"
                },
                {
                    "name": "GigabitEthernet1/0/1"
                },
                {
                    "name": "GigabitEthernet1/0/2"
                },
                {
                    "name": "GigabitEthernet1/0/3"
                },
                {
                    "name": "GigabitEthernet1/0/4"
                },
                {
                    "name": "GigabitEthernet1/0/5"
                },
                {
                    "name": "GigabitEthernet1/0/6"
                },
                {
                    "name": "GigabitEthernet1/0/7"
                },
                {
                    "name": "GigabitEthernet1/0/8"
                },
                {
                    "name": "GigabitEthernet1/0/9"
                },
                {
                    "name": "GigabitEthernet1/0/10"
                },
                {
                    "name": "GigabitEthernet1/0/11"
                },
                {
                    "name": "GigabitEthernet1/0/12"
                },
                {
                    "name": "GigabitEthernet1/0/13"
                },
                {
                    "name": "GigabitEthernet1/0/14"
                },
                {
                    "name": "GigabitEthernet1/0/15"
                },
                {
                    "name": "GigabitEthernet1/0/16"
                },
                {
                    "name": "GigabitEthernet1/0/17"
                },
                {
                    "name": "GigabitEthernet1/0/18"
                },
                {
                    "name": "GigabitEthernet1/0/19"
                },
                {
                    "name": "GigabitEthernet1/0/20"
                },
                {
                    "name": "GigabitEthernet1/0/21"
                },
                {
                    "name": "GigabitEthernet1/0/22"
                },
                {
                    "name": "GigabitEthernet1/0/23"
                },
                {
                    "name": "GigabitEthernet1/0/24"
                },
                {
                    "name": "GigabitEthernet1/1/1"
                },
                {
                    "name": "GigabitEthernet1/1/2"
                },
                {
                    "name": "TenGigabitEthernet1/1/3"
                },
                {
                    "name": "TenGigabitEthernet1/1/4"
                },
                {
                    "name": "Vlan1"
                }
            ]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_facts
##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /home/razvan/Documents/WiFiroedu/ansible_network/ansible.cfg
  configured module search path = ['/home/razvan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 29 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 15
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT

"ansible_net_model": "WS-C3650-24TD"
"ansible_net_system": "ios",
"ansible_net_version": "16.09.04",

and this happens on ASR1000 as well:
"ansible_net_model": "ASR1001-X",
"ansible_net_system": "ios",
"ansible_net_version": "16.06.04",

##### STEPS TO REPRODUCE

Get facts from ios device with gather_network_resources: l3_interfaces

```yaml
- name: 'Get facts'
  hosts: catalyst
  module_defaults:
    ios_facts:
      gather_network_resources: 'interfaces,l3_interfaces'
  gather_facts: true
```

##### EXPECTED RESULTS

I would expect the module to put only interfaces that have an IP address in the variable, just like nxos_facts does:
"l3_interfaces": [
                {
                    "ipv4": [
                        {
                            "address": "172.25.1.1/24"
                        }
                    ],
                    "name": "mgmt0"
                }
            ],

##### ACTUAL RESULTS

The module returns all interfaces even though they do not have ip addresses assigned.

```paste below
            "l3_interfaces": [
                {
                    "name": "Port-channel1"
                },
                {
                    "ipv4": [
                        {
                            "address": "172.25.1.1 255.255.255.0"
                        }
                    ],
                    "name": "GigabitEthernet0/0"
                },
                {
                    "name": "GigabitEthernet1/0/1"
                },
                {
                    "name": "GigabitEthernet1/0/2"
                },
                {
                    "name": "GigabitEthernet1/0/3"
                },
                {
                    "name": "GigabitEthernet1/0/4"
                },
                {
                    "name": "GigabitEthernet1/0/5"
                },
                {
                    "name": "GigabitEthernet1/0/6"
                },
                {
                    "name": "GigabitEthernet1/0/7"
                },
                {
                    "name": "GigabitEthernet1/0/8"
                },
                {
                    "name": "GigabitEthernet1/0/9"
                },
                {
                    "name": "GigabitEthernet1/0/10"
                },
                {
                    "name": "GigabitEthernet1/0/11"
                },
                {
                    "name": "GigabitEthernet1/0/12"
                },
                {
                    "name": "GigabitEthernet1/0/13"
                },
                {
                    "name": "GigabitEthernet1/0/14"
                },
                {
                    "name": "GigabitEthernet1/0/15"
                },
                {
                    "name": "GigabitEthernet1/0/16"
                },
                {
                    "name": "GigabitEthernet1/0/17"
                },
                {
                    "name": "GigabitEthernet1/0/18"
                },
                {
                    "name": "GigabitEthernet1/0/19"
                },
                {
                    "name": "GigabitEthernet1/0/20"
                },
                {
                    "name": "GigabitEthernet1/0/21"
                },
                {
                    "name": "GigabitEthernet1/0/22"
                },
                {
                    "name": "GigabitEthernet1/0/23"
                },
                {
                    "name": "GigabitEthernet1/0/24"
                },
                {
                    "name": "GigabitEthernet1/1/1"
                },
                {
                    "name": "GigabitEthernet1/1/2"
                },
                {
                    "name": "TenGigabitEthernet1/1/3"
                },
                {
                    "name": "TenGigabitEthernet1/1/4"
                },
                {
                    "name": "Vlan1"
                }
            ]
```

**Comment by mpsOxygen** [comment]
I found the problem, line 59 in ansible/module_utils/network/nxos/facts/l3_interfaces/l3_interfaces.py needs to change from:
                if obj:
to
                if obj and len(obj.keys()) > 1:

**Comment by GomathiselviS** [comment]
Hi @mpsOxygen  , As mentioned in the PR, this is the expected behavior. Hence closing this issue.
