### ISSUE TITLE
ios_facts for dot1x interface and for secondary user privileged

### ISSUE THREAD

**Issue by hyudra** [ansible-collections/cisco.ios#131]
##### SUMMARY
- I'm running with credentials that not privileged 15 and cannot get some facts (e.g. configuration , network_resources)
- I also would like to get any interface that have dot1x enabled for audit purposes

##### ISSUE TYPE
- For any 'show running-config' , is it possible to change to 'show running-config view full'  instead
- For dot1x, just return set of interfaces is suffice.

##### COMPONENT NAME
cisco.ios.ios_facts

**Comment by justjais** [comment]
@hyudra excuse me for the delayed response, and as this seems to be a very specific issue, we're not planning to implement in near future.

We welcome any of the community members to contribute and fix the respective issue. Closing the bug
