### ISSUE TITLE
cisco.ios.ios_l3_interfaces has wrong example for parsed

### ISSUE THREAD

**Issue by IPvSean** [ansible-collections/cisco.ios#132]
##### SUMMARY
in module docs here-> https://github.com/ansible-collections/cisco.ios/blob/main/docs/cisco.ios.ios_l3_interfaces_module.rst

it has under parsed 

>show running-config | include ip route|ipv6 route executed on device

where it should be

>show running-config | section ^interface.

(I think?). Documentation was probably copied from another module

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
cisco.ios.ios_l3_interfaces 

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /home/ec2-user/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

**Comment by justjais** [comment]
Doc fix already merged, hence closing the issue.
