### ISSUE TITLE
cisco.ios.ios_facts lag_interfaces not identifying all interfaces

### ISSUE THREAD

**Issue by venturawpg** [ansible-collections/cisco.ios#133]
##### SUMMARY

lag_interfaces, which is part of ios_facts gather_network_resources, is not always identifying interfaces that are part of an etherchannel. Have seen this on multiple models of Catalyst switches.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_facts:
  gather_network_resources:
    - lag_interfaces

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /home/user/git/ansible-testing/playbooks-testing/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/virtual-environments/ansible-python3/lib/python3.7/site-packages/ansible
  executable location = /home/user/virtual-environments/ansible-python3/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/home/user/git/ansible-testing/playbooks-testing/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco Catalyst WS-C4510R+E chassis switch
IOS version 03.08.09.E
WS-X45-SUP8-E supervisor cards in slots 5 and 6

Cisco Catalyst WS-C3850-48U-S
IOS version 16.06.07

##### STEPS TO REPRODUCE

See attached file for examples
[lag_interfaces_bug.txt](https://github.com/ansible-collections/cisco.ios/files/5211040/lag_interfaces_bug.txt)

```yaml
- name: GET ADDITIONAL FACTS NEEDED BY ROLE
  cisco.ios.ios_facts:
    gather_network_resources:
      - lag_interfaces

- name: PRINT ALL VARIABLES
  debug:
    msg: "{{ ansible_facts }}"
```

##### EXPECTED RESULTS

For both examples I would expect to see Port-channel1 in the lag_interfaces results along with the member interfaces.

##### ACTUAL RESULTS

As already mentioned the port-channel is missing from the results. For chassis switches it seems to miss the supervisor cards entirely.

Other observations:

- Supervisor line card interfaces DO appear in other facts gathering such as l2_interfaces.

- With the 3850 example, the config for physical interfaces of the uplink module actually appear twice - once for GigabitEthernet and once for TenGigabitEthernet. This is expected and how Cisco handles two different modes of operation. For example, Gi1/1/1 and Te1/1/1 correspond to the same physical SFP+ slot.

**interface GigabitEthernet1/1/1**
!
interface GigabitEthernet1/1/2
!
interface GigabitEthernet1/1/3
!
interface GigabitEthernet1/1/4
!
**interface TenGigabitEthernet1/1/1**
!
interface TenGigabitEthernet1/1/2
!
interface TenGigabitEthernet1/1/3
!
interface TenGigabitEthernet1/1/4

Just guessing here, but perhaps the issues has something to do with that.

```paste below

```

**Comment by justjais** [comment]
@venturawpg Thanks for raising the issue, can u please run the play again and share the complete verbose output (run play with `-vvvv` appended to your ansible-playbook run cmd) for the actual result.

**Comment by venturawpg** [comment]
Here is a run on the Catalyst 3850 with -vvvv. Output has been slightly sanitized, but nothing relevant to the bug was changed.
[3850_vvvv.txt](https://github.com/ansible-collections/cisco.ios/files/5283833/3850_vvvv.txt)

**Comment by justjais** [comment]
@venturawpg Thanks so much for pasting the verbose out, can u plz share the Port-channel lag config for which you're unable to get the facts structured data

**Comment by KB-perByte** [comment]
Closing as the issue is inactive

**Comment by donnerhacke** [comment]
Problem is in line 111 of ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/lag_interfaces/lag_interfaces.py

```
108-            return {}
109-        member_config = {}
110-        channel_group = utils.parse_conf_arg(conf, "channel-group")
111:        if intf.startswith("Gi"):
112-            config["name"] = intf
113-            config["members"] = []
114-            if channel_group:
```

It resticts the fact collection to GigabitEthernet only.
Please fix!
