### ISSUE TITLE
cisco.ios.ios_logging support for VRFs

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.ios#138]
SUMMARY
cisco.ios.ios_logging module doesn't currently support vrfs

ISSUE TYPE
Feature Idea
COMPONENT NAME
cisco.ios.ios_logging

ADDITIONAL INFORMATION
The feature is useful for people who manage boxes via a vrf instead of inband

**Comment by GomathiselviS** [comment]
@feisa  ios_logging resource module is on our roadmap. This issue will be addressed in the resource module.
