### ISSUE TITLE
cisco.ios.ios_logging not idempotent 

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.ios#139]
##### SUMMARY
cisco.ios.ios_logging  is not idempotent 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_logging 

##### ANSIBLE VERSION
ansible 2.9.13
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### OS / ENVIRONMENT
RHEL 8

##### STEPS TO REPRODUCE
- name: Configure Syslog IOS
  cisco.ios.ios_logging: 
    dest: host
    name: "{{ item }}"
    level: informational
    state: present 
  when: inventory_hostname not in groups["ios_routers_edge"] 
  with_items:
    - "{{ syslog_servers }}"
  tags:
    - ios-syslog

##### ACTUAL RESULTS

```
changed: [dc3-utilc001] => (item=splunk.com) => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "ansible_loop_var": "item",
    "changed": true,
    "commands": [
        "logging host splunk.com"
    ],
    "invocation": {
        "module_args": {
            "aggregate": null,
            "dest": "host",
            "facility": null,
            "level": "informational",
            "name": "splunk.com",
            "provider": null,
            "size": null,
            "state": "present"
        }
    },
    "item": "splunk.com"
```

**Comment by KB-perByte** [comment]
Hey @feisa looking at the commands that are there in the logs you shared, there seems like no specific command was triggered for _informational_, Please use _aggregate_ 
```    
        aggregate:
          - { "dest": "host", "name": "{{ item }}" }
          - { "level": "informational" }
        state: present
```
Thank you
