### ISSUE TITLE
ios_users always returns changed

### ISSUE THREAD

**Issue by bile0026** [ansible-collections/cisco.ios#157]
##### SUMMARY
ios_users module always returns as changed, even after multiple runs on the same device. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_user

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/zjbiles/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco Catalyst and ISR Devices

##### STEPS TO REPRODUCE

Using cisco.ios.ios_user with update_password: on_create seems to always update the password, so always returns changed even if user and correct password already exist. 

```yaml
- name: Ensure admin users exist
  cisco.ios.ios_user:
    name: '{{ local_user }}'
    hashed_password:
      type: 5
      value: '{{ local_pass }}'
    update_password: on_create
    privilege: 15
    state: present
  register: user_result
```

##### EXPECTED RESULTS

Task should not return hanged when user already exists. 

##### ACTUAL RESULTS

```paste below
Task run 1:
TASK [cisco_user_compliance : Ensure admin users exist] ************************
[WARNING]: Module did not set no_log for update_password
[WARNING]: Module did not set no_log for password_type
changed: [switch1]
changed: [switch2]
changed: [router1]
changed: [router2]

Task run 2:
TASK [cisco_user_compliance : Ensure admin users exist] ************************
[WARNING]: Module did not set no_log for update_password
[WARNING]: Module did not set no_log for password_type
changed: [switch1]
changed: [switch2]
changed: [router1]
changed: [router2]
```

**Comment by KB-perByte** [comment]
hey @bile0026,
As we are looking at `hashed_password` and specifying a hashed `type` we are not comparing the hash values at any point so a command to configure the same secret is always pushed in the target device. The non-idempotent behavior of the hashed_password attribute is expected. 
Thanks
