### ISSUE TITLE
Receive error: "unable to set terminal parameters" on IOS devices 

### ISSUE THREAD

**Issue by ros2020** [ansible-collections/cisco.ios#169]
##### SUMMARY
When attempting to run a playbook that uses 
ansible_connection: network_cli
ansible_network_os: cisco.ios.ios
against Cisco switches that has "privilege level 0" configured on the vty, the playbook fails with  "unable to set terminal parameters" error because the "terminal length 0" and "terminal width 512" commands are not permitted when in privilege 0. 

Similar to these issues: 
* [ios_command: "unable to set terminal parameters" error when vty is configured with "privilege level 0"](https://github.com/ansible/ansible/issues/44672)
* [error: "unable to set terminal parameters" on IOS devices ](https://github.com/ansible/ansible/issues/46185)

Tried to use become statements - did not work. 

Code base seems to indicate that on_open_shell executes before on_become
[refer](https://github.com/ansible/ansible/blob/e9a98b6ca94833993fea2c4a5a809356f3a27850/lib/ansible/plugins/connection/network_cli.py#L481-L487)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_command

##### ANSIBLE VERSION
```
ansible 2.9.5
```

##### OS / ENVIRONMENT

NAME="CentOS Linux"
VERSION="7 (Core)"
Docker version 19.03.6, build 369ce74a3c
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
postgres               10                  4ec80dedb917        7 months ago        255MB
ansible/awx_task       9.2.0               ca33e321fd9a        7 months ago        1.96GB
ansible/awx_web        9.2.0               40fd75c3154d        7 months ago        1.93GB
memcached              alpine              0dbf6b4c454b        8 months ago        9.19MB
ansible/awx_rabbitmq   3.7.4               e08fe791079e        2 years ago         85.6MB

##### STEPS TO REPRODUCE

In inventory the following variables: 
```
---
ansible_connection: network_cli
ansible_network_os: cisco.ios.ios
ansible_become: yes
ansible_become_method: enable
```

```---
- name: Hello World!
  hosts: all
  gather_facts: no
 
  tasks:  
    - name: run show version on remote devices
      cisco.ios.ios_command:  
        commands: show version 
      #become: yes
      #become_method: enable
```

##### EXPECTED RESULTS

The task and playbook complete successfully.

##### ACTUAL RESULTS

The playbook fails with a fatal "unable to set terminal parameters" error

```
"msg": "unable to set terminal parameters",

```

**Comment by justjais** [comment]
@ros2020 Thanks for logging the issue with the required details, can u share the persistent log for the use-case play run, you can enable persistent log following the respective doc: [enable logging](https://docs.ansible.com/ansible/devel/network/user_guide/network_debug_troubleshooting.html#enabling-networking-device-interaction-logging).
Also, run the play for full verbose out by running the play appended with `-vvvv`

**Comment by ros2020** [comment]
## Playbook
```yaml
---
- name: Hello World!
  hosts: all
  gather_facts: no
 
  tasks:
    - name: Ping
      ping:
      
    - name: Cisco Facts
      cisco.ios.ios_facts:
        gather_subset: all
      register: my_facts
      
    - name: Write Output
      debug:
         msg: "{{my_facts}}"
         
    - name: run show version on remote devices
      cisco.ios.ios_command:  
        commands: show version
      register: version_info  
      #become: yes
      #become_method: enable
```

## Output
ansible-playbook 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
Using /etc/ansible/ansible.cfg as config file
SSH password: 
BECOME password[defaults to SSH password]: 
setting up inventory plugins
host_list declined parsing /tmp/awx_251_b46zj6qy/tmpc03xdi1p as it did not pass its verify_file() method
Parsed /tmp/awx_251_b46zj6qy/tmpc03xdi1p inventory source with script plugin
Loading callback plugin awx_display of type stdout, v2.0 from /var/lib/awx/venv/awx/lib/python3.6/site-packages/ansible_runner/callbacks/awx_display.py
PLAYBOOK: hello-world.yml ******************************************************
Positional arguments: hello-world.yml
verbosity: 4
ask_pass: True
remote_user: YYYY
connection: smart
timeout: 10
become_method: enable
become_user: YYYY
become_ask_pass: True
tags: ('all',)
inventory: ('/tmp/awx_251_b46zj6qy/tmpc03xdi1p',)
extra_vars: ('@/tmp/awx_251_b46zj6qy/env/extravars',)
forks: 5
1 plays in hello-world.yml
PLAY [Hello World!] ************************************************************
META: ran handlers
TASK [Ping] ********************************************************************
task path: /tmp/awx_251_b46zj6qy/project/hello-world.yml:7
<172.19.164.190> attempting to start connection
<172.19.164.190> using connection plugin network_cli
<172.19.134.62> attempting to start connection
<172.19.134.62> using connection plugin network_cli
<172.19.134.62> local domain socket does not exist, starting it
<172.19.134.62> control socket path is /var/lib/awx/.ansible/pc/f4daf3d33e
<172.19.134.62> local domain socket listeners started successfully
<172.19.134.62> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /tmp/awx_251_b46zj6qy/requirements_collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os cisco.ios.ios
<172.19.134.62> 
<172.19.134.62> local domain socket path is /var/lib/awx/.ansible/pc/f4daf3d33e
<172.19.134.62> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.19.134.62> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0526688-253716743424139 `" && echo ansible-tmp-1601967068.0526688-253716743424139="` echo /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0526688-253716743424139 `" ) && sleep 0'
<172.19.164.190> local domain socket does not exist, starting it
<172.19.164.190> control socket path is /var/lib/awx/.ansible/pc/b63dfc4ed9
<172.19.164.190> local domain socket listeners started successfully
<172.19.164.190> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /tmp/awx_251_b46zj6qy/requirements_collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os cisco.ios.ios
<172.19.164.190> 
<172.19.164.190> local domain socket path is /var/lib/awx/.ansible/pc/b63dfc4ed9
<172.19.164.190> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.19.164.190> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0833306-196898378911038 `" && echo ansible-tmp-1601967068.0833306-196898378911038="` echo /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0833306-196898378911038 `" ) && sleep 0'
<172.19.134.62> Attempting python interpreter discovery
<172.19.134.62> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<172.19.164.190> Attempting python interpreter discovery
<172.19.164.190> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<172.19.134.62> EXEC /bin/sh -c '/var/lib/awx/venv/ansible/bin/python3.6 && sleep 0'
<172.19.164.190> EXEC /bin/sh -c '/var/lib/awx/venv/ansible/bin/python3.6 && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/system/ping.py
Using module file /usr/lib/python3.6/site-packages/ansible/modules/system/ping.py
<172.19.164.190> PUT /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/tmpxfxgske9 TO /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0833306-196898378911038/AnsiballZ_ping.py
<172.19.134.62> PUT /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/tmpjemax1u9 TO /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0526688-253716743424139/AnsiballZ_ping.py
<172.19.134.62> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0526688-253716743424139/ /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0526688-253716743424139/AnsiballZ_ping.py && sleep 0'
<172.19.164.190> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0833306-196898378911038/ /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0833306-196898378911038/AnsiballZ_ping.py && sleep 0'
<172.19.164.190> EXEC /bin/sh -c '/usr/libexec/platform-python /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0833306-196898378911038/AnsiballZ_ping.py && sleep 0'
<172.19.134.62> EXEC /bin/sh -c '/usr/libexec/platform-python /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0526688-253716743424139/AnsiballZ_ping.py && sleep 0'
<172.19.164.190> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0833306-196898378911038/ > /dev/null 2>&1 && sleep 0'
ok: [172.19.164.190] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "data": "pong"
        }
    },
    "ping": "pong"
}
<172.19.134.62> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-local-7870ind5rt8y/ansible-tmp-1601967068.0526688-253716743424139/ > /dev/null 2>&1 && sleep 0'
ok: [172.19.134.62] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "data": "pong"
        }
    },
    "ping": "pong"
}
TASK [Cisco Facts] *************************************************************
task path: /tmp/awx_251_b46zj6qy/project/hello-world.yml:10
<172.19.134.62> attempting to start connection
<172.19.134.62> using connection plugin network_cli
<172.19.164.190> attempting to start connection
<172.19.164.190> using connection plugin network_cli
<172.19.134.62> found existing local domain socket, using it!
<172.19.134.62> updating play_context for connection
<172.19.134.62> 
<172.19.134.62> local domain socket path is /var/lib/awx/.ansible/pc/f4daf3d33e
<172.19.164.190> found existing local domain socket, using it!
<172.19.164.190> updating play_context for connection
<172.19.164.190> 
<172.19.164.190> local domain socket path is /var/lib/awx/.ansible/pc/b63dfc4ed9
fatal: [172.19.134.62]: FAILED! => {
    "changed": false,
    "msg": "unable to set terminal parameters"
}
fatal: [172.19.164.190]: FAILED! => {
    "changed": false,
    "msg": "unable to set terminal parameters"
}
PLAY RECAP *********************************************************************
172.19.134.62              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
172.19.164.190             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by ros2020** [comment]
@justjais Please note also that when I switched the order of the [calls ](https://github.com/ansible/ansible/blob/e9a98b6ca94833993fea2c4a5a809356f3a27850/lib/ansible/plugins/connection/network_cli.py#L481-L487) for **on_become** and **on_open_shell**, so that  on_become is called first - then my playbook is working.

**Comment by justjais** [comment]
@Qalthos can you plz check the issue and update

**Comment by Qalthos** [comment]
This appears to have been fixed for the entire lifetime of the ansible.netcommon collection, and was backported to 2.9 last year.

If you are still experiencing this problem, please update ansible and/or install the [ansible.netcommon](https://galaxy.ansible.com/ansible/netcommon) collection
