### ISSUE TITLE
Backup Process

### ISSUE THREAD

**Issue by itdependsnetworks** [ansible-collections/cisco.ios#185]
##### SUMMARY

Clarification of how backup process works. From observing the code, the only thing that I see setting the code is:

```
        if module.params['backup']:
            result['__backup__'] = contents
```
 Presumably there is some other process that understands to copy `result['__backup__']` to the `filename` location. Can someone confirm how this works, and if all of the code is included in the collection or needs to come from 2.10 only code? 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
dunder backup e.g. `result['__backup__']`

##### ANSIBLE VERSION
```paste below
2.9
```

**Comment by KB-perByte** [comment]
Hi @itdependsnetworks, the way network modules work, is changed considering Ansible version 2.10+ 
you can refer to the docs, [Ansible for Network Automation](https://docs.ansible.com/ansible/latest/network/index.html for information) on the same.
