### ISSUE TITLE
IOS facts module - rerieve all filesystems information and mac address for stacks

### ISSUE THREAD

**Issue by slefol** [ansible-collections/cisco.ios#208]
##### SUMMARY
It would be interesting to have the information on all files systems present on the device.
And to have the mac addresses of all the members for a stack.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cisco.ios.ios_facts

##### ANSIBLE VERSION
ansible 2.9.6

##### ADDITIONAL INFORMATION
module_utils/network/ios/facts/legacy/base.py
- replace 'dir' by 'dir all-filesystems'
- add stacked_macs to facts

```
class Hardware(FactsBase):
    COMMANDS = [
        'dir all-filesystems',
        'show memory statistics'
    ]

class Default(FactsBase):
    def parse_stacks(self, data):
        match = re.findall(r'Base [Ee]thernet MAC [Aa]ddress\s+: (\S+)', data, re.M)
        if match:
            self.facts['stacked_macs'] = match
```

**Comment by lorephoenix** [comment]
**COMPONENT NAME**
cisco.ios.ios_facts

**ANSIBLE VERSION**
Ansible version 2.10

**ADDITIONAL INFORMATION**
Ansible collections
- ansible.netcommon 1.4.1
- cisco.ios 1.2.1

Python version 3.6.7

Gather facts around IOS hardware doesn't provide me the correct values behind the key
ansible_net_filesystems and ansible_net_filesystems_info.

The following Cisco IOS commands provide me below information from my device "ios-device"
```
ios-device#show run | include  provision
switch 1 provision ws-c2960s-48ts-l
switch 2 provision ws-c2960s-24ps-l
switch 3 provision ws-c2960s-48ts-l

ios-device#show switch
Switch/Stack Mac Address : 88f0.xxxx.4100
                                           H/W   Current
Switch#  Role   Mac Address     Priority Version  State
----------------------------------------------------------
*1       Master 88f0.xxxx.4100     15     1       Ready
2       Member e8ba.xxxx.8880     10     1       Ready
3       Member 6886.xxxx.b080     1      1       Ready
```

Running cisco.ios.ios_facts provides me the following information:
```
"ansible_net_filesystems": [    "flash:"   ]
"ansible_net_filesystems_info": {
        "flash:": {
                 "spacefree_kb": 3665.5,
                 "spacetotal_kb": 56574.0
        }
  }
```
The values behind those keys are coming from the member that is set as a master but it doesn't include the filesystem info from all other connected members. I expected to get the following:

```
"ansible_net_filesystems": [ "flash1:", "flash2:", "flash3:" ]
"ansible_net_filesystems_info": {
        "flash1:": {
            "spacefree_kb": 3665.5,
            "spacetotal_kb": 56574.0
        },
	"flash2:": {
            "spacefree_kb": 3661.0,
            "spacetotal_kb": 56578.0
        },
	"flash3:": {
            "spacefree_kb": 3600.5,
            "spacetotal_kb": 56650.0
        }
    }

```
