### ISSUE TITLE
Add gathered, rendered, parsed support to the `Ansible 2.9` Resource Modules

### ISSUE THREAD

**Issue by justjais** [ansible-collections/cisco.ios#27]
##### SUMMARY

Add gathered, rendered, parsed support to the `Ansible 2.9` Resource Modules:

- [x]  ios_interfaces
- [x]  ios_l2_interfaces
- [x]  ios_l3_interfaces
- [x]  ios_lacp
- [x]  ios_lacp_interfaces
- [x]  ios_lag_interfaces
- [x]  ios_lldp_global
- [x]  ios_lldp_interfaces
- [x]  ios_vlans

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ios

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by trishnaguha** [comment]
Please take care of adding fully qualified collection name in the examples for these modules in the same PRs as well.

**Comment by justjais** [comment]
sure
