### ISSUE TITLE
Private argument spec validation methods no longer available in Ansible Core 2.11

### ISSUE THREAD

**Issue by samdoran** [ansible-collections/cisco.ios#281]
##### SUMMARY

Argument spec validation has changed in Ansible Core 2.11. The following private method calls should be changed to use the public interface:

```
cisco.ios/plugins/modules/ios_logging.py
405:            module._check_required_if(required_if, item)  # --> ansible.module_utils.common.validation.check_required_if()

cisco.ios/plugins/modules/ios_vrf.py
586:        type_checker = module._CHECK_ARGUMENT_TYPES_DISPATCHER[value_type]  # --> ansible.module_utils.parameters.DEFAULT_TYPE_VALIDATORS

cisco.ios/plugins/modules/ios_static_route.py
311:            module._check_required_together(required_together, route)  # --> ansible.module_utils.common.check_required_together()
314:        module._check_required_together(required_together, module.params)  # --> ansible.module_utils.common.check_required_together()

cisco.ios/plugins/modules/ios_user.py
486:        type_checker = module._CHECK_ARGUMENT_TYPES_DISPATCHER[value_type]  # --> ansible.module_utils.parameters.DEFAULT_TYPE_VALIDATORS
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`ios_logging.py`
`ios_vrf.py`
`ios_static_route.py`
`ios_user.py`
##### ANSIBLE VERSION

```paste below
2.11
```

**Comment by Qalthos** [comment]
We can't move to the new location while we support versions < 2.11, and the private attribute will persist for the foreseeable future.

I'm keeping the original issue at ansible-collections/ansible.netcommon#186 open for now to coordinate efforts around replacing it if and when that becomes feasible
