### ISSUE TITLE
Documentation Link Error

### ISSUE THREAD

**Issue by jvanderaa** [ansible-collections/cisco.ios#293]
##### SUMMARY

https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_config_module.html contains an error that the link for `Abbreviated commands are NOT idempotent` is not showing up

Also: `HINT: Did you know the documentation has an "Edit on GitHub" link on every page ?` in the template is inaccurate. There is not a link on the documentation page today

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

ios_config

##### ANSIBLE VERSION
3

**Comment by KB-perByte** [comment]
Hey @jvanderaa,
[PR](https://github.com/ansible-collections/cisco.ios/pull/368) would fix the issue. Thanks for reporting the issue.

**Comment by ganeshrn** [comment]
The Edit on Github issue is tracked by https://github.com/ansible/ansible/issues/70267
