### ISSUE TITLE
cisco.ios.ios_bgp support for vrfs

### ISSUE THREAD

**Issue by aaronhuff** [ansible-collections/cisco.ios#314]
##### SUMMARY
cisco.ios.ios_bgp does not support vrfs

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cisco.ios.ios_bgp

##### ADDITIONAL INFORMATION
the module does not support vrfs, anyone creating bgp configuration for a vrf cannot use this module.

```
router bgp 65500
 address-family ipv4 vrf test
  bgp router-id 10.0.0.1
  redistribute connected
  neighbor 10.0.0.2 remote-as 65501
 exit-address-family
```

**Comment by justjais** [comment]
@aaronhuff there's a newer RM ios_bgp_global is available which supports VRF, can you try the respective module and let me know if that works out for you as expected.

**Comment by aaronhuff** [comment]
@justjais Thanks, I tried all three of the modules and had limitations with each. But if that's the newer one, let me test it again and see what the obstruction was. Trying to avoid working around it with a bunch of custom cli_conf based tasks which will lack proper idempotency.

**Comment by justjais** [comment]
@aaronhuff sure, going forward `ios_bgp` module is planned to be deprecated, and if you feel there's some limitation or something needs to be added or updated feel free to raise the feature/bug request against the newer RM i.e. [ios_bgp_global](https://github.com/ansible-collections/cisco.ios/blob/main/docs/cisco.ios.ios_bgp_global_module.rst#ciscoiosios_bgp_global) and [ios_bgp_address_family](https://github.com/ansible-collections/cisco.ios/blob/main/docs/cisco.ios.ios_bgp_address_family_module.rst#ciscoiosios_bgp_address_family)
