### ISSUE TITLE
cisco.ios.ios_bgp gather operation

### ISSUE THREAD

**Issue by aaronhuff** [ansible-collections/cisco.ios#315]
##### SUMMARY
cisco.ios.ios_bgp does not have a gathered operation

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

cisco.ios.ios_bgp

##### ADDITIONAL INFORMATION

the module does not have a gather operation to fetch and transform existing bgp configuration into structure data

**Comment by justjais** [comment]
@aaronhuff there's a newer RM [ios_bgp_global](https://github.com/ansible-collections/cisco.ios/blob/main/docs/cisco.ios.ios_bgp_global_module.rst#ciscoiosios_bgp_global) and [ios_bgp_address_family](https://github.com/ansible-collections/cisco.ios/blob/main/docs/cisco.ios.ios_bgp_address_family_module.rst#ciscoiosios_bgp_address_family) is available which supports all the newer supported operations including gathered for getting the facts in structured data format.
Can you try the respective module and let me know if that works out for you as expected.

**Comment by aaronhuff** [comment]
@justjais will do, I had a bug because of my use of peergroups with them.. so I will log it and do a cli_config manual workaround.
