### ISSUE TITLE
'ios_acls' module does not work

### ISSUE THREAD

**Issue by ishii-h** [ansible-collections/cisco.ios#328]
##### SUMMARY

The cisco.ios.ios.acls module does not work.
Is there anything else I need to do other than install the collection?
The "ios_command" and "ios_config" modules are working, but does the "ios_acls" module need something else? 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.10.7
config file = None
configured module search path = ['/home/gmone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### AWX VERSION

```paste below
15.0.0
```

##### CentOS VERSION

```paste below
$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
```
##### Cisco.ios Collection version VERSION

```paste below
# ansible-galaxy collection list
# /root/.ansible/collections/ansible_collections
Collection Version
----------------- -------
ansible.netcommon 2.0.1
ansible.utils 2.0.2
cisco.ios 2.0.0
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT

```paste below
#sh ver
Cisco IOS XE Software, Version 03.12.00.S - Standard Support Release
Cisco IOS Software, CSR1000V Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 15.4(2)S, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2014 by Cisco Systems, Inc.
Compiled Wed 26-Mar-14 21:09 by mcpre
```

##### STEPS TO REPRODUCE

```yaml
---
 - name: acl_ios_config_test
   hosts: all
   gather_facts: no
   become: yes
 
   vars:
     ansible_connection: network_cli
     ansible_network_os: ios
 
   tasks:
   - name: 'Delete ALL'
     cisco.ios.ios_acls:
       state: deleted
```

##### ACTUAL RESULTS

```paste below
ERROR! couldn't resolve module/action 'cisco.ios.ios_acls'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/tmp/awx_450_fmq5jt4r/project/acls_del.yml': line 13, column 6, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
   - name: 'Delete ALL'
     ^ here

```

**Comment by justjais** [comment]
@ishii-h Going by the error shown under actual results, it seems like `ios_acls` module is not getting picked from the collection installed, can u plz verify if other resource module like `ios_interfaces/ios_bgp_global` works in your environment or that also gives the similar error.

**Comment by ishii-h** [comment]
@justjais Thank you for your reply.
I also tried other resource modules such as 'ios_interfaces / ios_bgp_global' and got the same result.

**Comment by justjais** [comment]
@ishii-h hmm, seems like ansible is not able to find the ios collection modules as expected, but ideally it should going by the ios collections installation under galaxy as mentioned in the issue comment. Can you plz verify if under `/root/.ansible/collections/ansible_collections` ->`cisco/ios` collections is present and under respective `ios` folder `plugins->modules->ios_acls/ios_interfaces/ios_bgp_global `n other RM are present

**Comment by ishii-h** [comment]
@justjais Files such as `ios_acls / ios_interfaces / ios_bgp_global`exist in the corresponding directory.
Should I install the collection from inside the docker container?
I installed the collection with root privileges.

**Comment by justjais** [comment]
@ishii-h it's strange it's able to run the ios_config/command module as those are also present under same dir str., and you've mentioned from inside the docker container are you trying to run the command from within the container?

**Comment by ishii-h** [comment]
Since it was stated that ansible-galaxy install is executed with awx_task at the following URL, I asked a question.
https://github.com/aruba/aos-switch-ansible-collection/issues/4

However, since ios_command and ios_config can be used, it becomes strange...

**Comment by akira6592** [comment]
@ishii-h How about changing the path to install the collection?

```
ansible-galaxy collection install cisco.ios -p /var/lib/awx/.ansible/collections
```
on `awx_task`

**Comment by akira6592** [comment]
Alternatively, you can specify the required collection in `[Project Top]/collections/requirements.yml` and install it dynamically.

https://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html#collections-support

example: `[Project Top]/collections/requirements.yml`

```yaml
---
collections:
  - name: cisco.ios
    version: 2.0.0
```

**Comment by ishii-h** [comment]
@akira6592 thank you so much!! 
I was able to work based on your advice!
