### ISSUE TITLE
Cisco SD-WAN vManage  - On open shell command (terminal length 0 ) not supported using “cisco.ios.ios_command” module 

### ISSUE THREAD

**Issue by satishkamavaram** [ansible-collections/cisco.ios#349]
##### SUMMARY

“cisco.ios.ios_command” module on opening a connection to SD-WAN vManage executes a default CLI command “terminal length 0” which is not supported by Cisco SD-WAN vManage command line . Due to this , Ansible script using ios_command module fails to run through native Cisco SD-WAN vManage CLI commands.

It would be great to determine if it is SD-WAN mode , don't execute the default OnOpenShell command "terminal length 0" or have a different command which works in SD-WAN mode also.

Another approach , probably create temp file on open shell and delete temp file on close shell. ( I see there is a "on_close_shell" callback method available in TerminalBase class  which we can override in https://github.com/ansible-collections/cisco.ios/blob/main/plugins/terminal/ios.py module)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_command”

##### ANSIBLE VERSION

```paste below
2.10.9
```

##### CONFIGURATION

```paste below
python version : 3.9.0
```

##### OS / ENVIRONMENT

MAC OS

##### STEPS TO REPRODUCE

Add below task in Ansbile playbook by pointing to SD-WAN vManage host (replace placeholder below) and run the playbook

```yaml
- hosts: "{{ vManageHost }}”
  connection: network_cli
  tasks:
    - name: create backups folder in vManage
      cisco.ios.ios_command: 
        commands: request execute mkdir backups
```

##### EXPECTED RESULTS

  The above task should be able to create "backups" directory under /home/admin/

##### ACTUAL RESULTS

```paste below
    The above task fails with 
fatal: [vManageHost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "request execute mkdir backups"
            ],
            "interval": 1,
            "match": "all",
            "provider": null,
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "unable to set terminal parameters"
}

```

##### ADDITIONAL INFORMATION
```
Refer below code where default on open shell command getting executed

https://github.com/ansible-collections/cisco.ios/blob/main/plugins/terminal/ios.py

def on_open_shell(self):     
   try:           
 self._exec_cli_command(b"terminal length 0")     
   except AnsibleConnectionFailure:           
 raise AnsibleConnectionFailure("unable to set terminal parameters")
```

**Comment by KB-perByte** [comment]
Hi @satishkamavaram, 
you are trying to push an SD-WAN vManage host's native command via the ios_command module, which is not recommended as the expectation is the commands are directly applied to the IOS box targeted, in this case, we have SD-WAN infra in between. I could find some [roles](https://github.com/CiscoDevNet/sdwan-ansible-code) in DevNet that lets you connect to SD-WAN and use the feature template to interact with the system, perhaps can you help us with the configuration you are using for us to better understand your need.

**Comment by satishkamavaram** [comment]
Thanks @KB-perByte  .. Configuration is available in the description adding here again, we use lot of CLI commands listing few here , kindly let me know if you need more details

**Sample commands** :
1. request nms application-server restart
2. request nms all status
3. request nms configuration-db backup path /home/admin/backups/db_backup

**sample.yml** :
- hosts: "{{ vManageHost }}”
  connection: network_cli
  tasks:
    - name: create backups folder in vManage
      cisco.ios.ios_command: 
        commands: request execute mkdir backups

**hosts** :
[vManage]
vManage202 ansible_host=10.5.113.223

[vManage:vars]
ansible_network_os=ios
ansible_connection=network_cli
ansible_user=admin
ansible_password=admin

**Comment by KB-perByte** [comment]
Hi @satishkamavaram,
So as I mentioned Sd-WAN already has roles for [viptela](https://github.com/CiscoDevNet/sd-wan-ansible-pipeline-code/tree/master/roles) defined for its API calls to the vManage nodes, This would be a wrong way of using the IOS module as the vManage target system is not as per the configuration 
```
ansible_network_os=ios
ansible_connection=network_cli
```
You can try with the [sd-wan-ansible-pipeline](https://github.com/CiscoDevNet/sd-wan-ansible-pipeline-code) for your use case.
Thank you!

**Comment by KB-perByte** [comment]
Hey, @satishkamavaram we added a patch to the terminal plugin to support SD-wan and reopened the issue reported. Please check the reported use case considering the changes in the PR.
Thanks.

**Comment by satishkamavaram** [comment]
@KB-perByte  Thanks for getting back and letting me know. It works perfectly. When this change would be published to galaxy?

**Comment by KB-perByte** [comment]
Hi @satishkamavaram, it would be available in galaxy after this month's release for `cisco.ios v2.5.0`.
Thanks for verifying the fix.
