### ISSUE TITLE
ios_user always pushes command when hashed_password is set

### ISSUE THREAD

**Issue by mtinberg** [ansible-collections/cisco.ios#357]
https://github.com/ansible-collections/cisco.ios/blob/a65ab7d5d713208e35bf236cda55b87084b2fbe7/plugins/modules/ios_user.py#L469

ios_user doesn't parse the hashed password for existing local accounts so the check to needs_update will never not be true

https://github.com/ansible-collections/cisco.ios/blob/a65ab7d5d713208e35bf236cda55b87084b2fbe7/plugins/modules/ios_user.py#L412

This means that passwords set with ios_user will _always_ trigger a config change even when nothing has changed.

Is this intended behavior or would you like a parse_hashed_password function that checks for secret and populates a type 5, 8 or 9 credential?  there may be different behavior for password entries with type 7 hashes as those are decodable so could be compared with a configured_password.

Is this a change which would be accepted?

**Comment by KB-perByte** [comment]
Hi @mtinberg,
This is the intended behavior of the module as hashed passwords are supposed to use multiple hash values that are not compared by the module. Hence, it will always trigger a command when we run the same play multiple times.
Thanks.

**Comment by mtinberg** [comment]
If one is providing a pre-calculated hash to the module rather than a clear text password then I think comparing it is the right thing to do, and if one compares a clear text password with the hashed value then it will always trigger an update, which is the same behavior as today.

In this case I'm switching to using the ios_config module as the only advantage of ios_user for me would be if I were pushing SSH public keys, which I am not at this time and I still need to support outdated device versions that don't have show running-config | section username​ which I think is the blocker.

Thanks for taking a look.


—

Mark Tinberg ***@***.***>

Division of Information Technology-Network Services

University of Wisconsin-Madison


________________________________
