### ISSUE TITLE
Detection of Virtual Switch System on IOS based Switches

### ISSUE THREAD

**Issue by tweippert** [ansible-collections/cisco.ios#46]
##### SUMMARY
With IOS/IOS-XE based switches (on some plattforms C4500X, C650X-E, C6800) it is possible
to form a Virtual Switch System (VSS) from two physical switches. The current fact module for ios is capable to detect "stacked" switches but not "Virtual Switch System"

If a VSS is detected, one or two additional facts will/can be added, e.g.:

```
        "net_virtual_switch": "VSS",
        "net_virtual_switch_domain": "102",
```
The fact net_virtual_switch_domain is the needed switch virtual domain configuration. The other fact can be ommited, maybe only the domain is enough. Sometimes it may be nice to had a single fact which differs between "virtual_switch variants". VSS and STACK can be the current ones for IOS/IOS-XE. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ios_facts

##### ADDITIONAL INFORMATION

I had a working patch and can issue an pull request in the next days if this is
acceptable.

**Comment by justjais** [comment]
PR with the fix is already merged, closing the bug
