### ISSUE TITLE
Privilege password ios_user

### ISSUE THREAD

**Issue by ramuskay** [ansible-collections/cisco.ios#468]
##### SUMMARY
Hi,

When i tried to add a user with a password it worked but if i want to add some privilege i got an error with the message "incomplete command". When i remove the privilege the account is created

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_user

##### ANSIBLE VERSION

```
2.11.6
```

##### COLLECTION VERSION
```
[root@ansible-par inventory]# ansible-galaxy collection list  cisco.ios

# /root/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  2.6.0  
```

##### CONFIGURATION
```
[root@ansible-par inventory]# ansible-config dump --only-changed
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
[root@ansible-par inventory]# 
```

##### OS / ENVIRONMENT
```
[root@ansible-par inventory]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core
```

##### STEPS TO REPRODUCE

```
  - name: test_user
    cisco.ios.ios_user:
      aggregate:
      - name: netop
        hashed_password:
          type: 5
          value: $1$dsiX$av5Yl/LkpdNvidDL8XtzK.
      - name: netend
        hashed_password:
          type: 5
          value: $1$dsiX$av5Yl/LkpdNvidDL8XtzK.
      privilege: 15
      state: present
```
I took an official example and added a password configuration (without it didn't work either)
But when i remove the parameter privilege it's working
The remote switch 2960X is in version 15.2(7)E4 (maybe related to the bug https://quickview.cloudapps.cisco.com/quickview/bug/CSCvy40917)

##### EXPECTED RESULTS

```
TASK [test_user] ************************************************************************************************
[WARNING]: Module did not set no_log for password_type
[WARNING]: Module did not set no_log for update_password
changed: [switch-ab]
```

##### ACTUAL RESULTS

```
TASK [test_user] ************************************************************************************************
[WARNING]: Module did not set no_log for password_type
[WARNING]: Module did not set no_log for update_password
fatal: [switch-ab]: FAILED! => {"changed": false, "msg": "username netop privilege 15\r\nusername netop privilege 15\r\n% Incomplete command.\r\n\r\nswitch-ab(config)#"}
```

**Comment by ramuskay** [comment]
Hi,

So i finally figured out, the module doesn't create a user with one big line but with multiple lines. Ex if i provide a privlege and a password:
```
username netend privilege 15
username netend secret 5 $1$dsiX$6ngcWvzxcCRK9tGelx0uY/
```
But due to the bug CSCvy40917 (https://quickview.cloudapps.cisco.com/quickview/bug/CSCvy40917) we can not create an user without specifying a pasword.
So have we to adapt the module or wait for a patch IOS release ?

Regards

**Comment by KB-perByte** [comment]
Hey, @ramuskay yes, your findings were right that is a bug from Cisco's side for not accepting the username resource command is supplied by the resource in form of two commands other than one single command. AFAIK it affects a single version as mentioned. It would be recommended to wait for the path on the IOS release for this to be fixed.
Thanks

**Comment by ramuskay** [comment]
Ok thank you i'll wait :)
