### ISSUE TITLE
Cisco Ios SNMP Server V3 Auth and Priv Passwords

### ISSUE THREAD

**Issue by mohameddjelouah** [ansible-collections/cisco.ios#478]
##### SUMMARY

Hello,
in the module cisco ios snmp server in groups and users if i specified version v3 and version_option auth or priv i cant find an option to add the auth key or the priv key if i excuted the playbok it said incomplete command so please help me i need snmpv3 with auth and priv keys.   

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by KB-perByte** [comment]
hey @mohameddjelouah can you please share the playbook in which you faced the following issue, 'reporting incomplete commands'? 
Do consider the `groups` and `users` key contains all the common attributes for all the `version_option` all at once, it is for the best judgment of the user to use the options that make sense with a combination of any attribute value.
Thanks.

**Comment by mohameddjelouah** [comment]
> hey @mohameddjelouah can you please share the playbook in which you faced the following issue, 'reporting incomplete commands'? Do consider the `groups` and `users` key contains all the common attributes for all the `version_option` all at once, it is for the best judgment of the user to use the options that make sense with a combination of any attribute value. Thanks.

this is the platbook in the docs there no mention of priv and auth keys this playbook will give me a incomplete command because theres no priv and auth keys  thank you

- name: test
  hosts: x.x.x.x
  vars:
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: ******
    ansible_password: *******
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: ******

  tasks:
   - name: SNMPV3
     cisco.ios.ios_snmp_server:
       config:
         location: 'location'
         contact: 'Network-Team'
         groups:
         -   group: snmp
             version: v3
             version_option: priv
         users:
         -   group: snmp
             username: admin
             version: v3
             version_option: auth

**Comment by KB-perByte** [comment]
hey, @mohameddjelouah unable to understand how the issue reported is considered under snmp_server context? 
Can you please share the commands that you intend to fire for the same? As the group attribute is not supposed to take a key as input.

**Comment by mohameddjelouah** [comment]
> hey, @mohameddjelouah unable to understand how the issue reported is considered under snmp_server context? Can you please share the commands that you intend to fire for the same? As the group attribute is not supposed to take a key as input.

yes group is not supported to take a key but user is 
this is the commands 

snmp-server group <GROUP-NAME> v3 priv
snmp-server user <USER-NAME> <GROUP-NAME> v3 auth sha <AUTH-PASSWORD> priv aes 128 <PRIV-PASSWORD>
snmp-server contact <YOUR-CONTACT>
snmp-server location <YOUR-LOCATION>

so where to put the <AUTH-PASSWORD> and  <PRIV-PASSWORD> what attribute and where thank you.

**Comment by KB-perByte** [comment]
Hey, @mohameddjelouah I see the `auth_password `attributes missing for `users `as it was not considered in the module previously, I am adding an action item on this, we would consider them as a feature request in the upcoming release.
Thanks for reporting.

**Comment by KB-perByte** [comment]
Hey @mohameddjelouah, while adding the options I saw a weird behavior of the IOS box or the version I am using, i.e, I am unable to find the lines within running-config once configuring user with `v3` `auth` followed by `sha` and `priv`, for version_option other than v3 the lines are found in running-config. Can you please confirm if the case is similar across the version you are using? you can use `show running-config | section ^snmp-server` to verify.
Thanks in advance.

**Comment by mohameddjelouah** [comment]
> o find the lines within running-config once configuring user with `v3` `auth` followed by `sha` and `priv`, for version_option other than v3 the lines are found in running-config. Can you please confirm if th



> Hey @mohameddjelouah, while adding the options I saw a weird behavior of the IOS box or the version I am using, i.e, I am unable to find the lines within running-config once configuring user with `v3` `auth` followed by `sha` and `priv`, for version_option other than v3 the lines are found in running-config. Can you please confirm if the case is similar across the version you are using? you can use `show running-config | section ^snmp-server` to verify. Thanks in advance.

yes theres no  information there but if you excute show snmp user you will see al the details relating to that user for example 

User name: admin
Engine ID: ******
storage-type: nonvolatile        active
Authentication Protocol: SHA
Privacy Protocol: AES128
Group-name: SomeGroup
