### ISSUE TITLE
state gathered returns missing argument as_number

### ISSUE THREAD

**Issue by ljankok** [ansible-collections/cisco.ios#507]
Standard playbook
- name: Gather listed global BGP with provided configurations
  cisco.ios.ios_bgp_global:
    config:
    state: gathered

Output:
msg: missing required arguments: as_number found in config

Piece of BGP configuration on Catalyst 9500

router bgp 65100.65412
  template peer-policy pp_exa_dn_pri
...
  template peer-session DNR
    remote-as 65123
...  
  bgp router-id 10.10.10.10
  bgp asnotation dot
...
 address-family ipv4 vrf next
...

**Comment by empusas** [comment]
Same problem here. Does not seem to like 4 byte ASN in ASDOT format

**Comment by KB-perByte** [comment]
Hey @empusas @ljankok,
Thanks for reporting the issue. 
I am looking at the fix for ios_bgp_global considering the issues and some feature requests. The issues are planned to be addressed in next month's release.
Regards
