### ISSUE TITLE
expand scope of the l2_interfaces module with 'show derived-config | section ^interface'

### ISSUE THREAD

**Issue by ljankok** [ansible-collections/cisco.ios#512]
##### SUMMARY
Enhance  l2_interfaces module with 'show derived-config | section ^interface'

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
l2_interfaces module

##### ADDITIONAL INFORMATION
The l2_interfaces module derives its facts from the command 'show running-config | section ^interface'.
Due to the limitation of this command, the module will miss Layer 2 configuration when interface templates have been applied.
To have the l2_interfaces module also catch the l2 characteristics of an interface when interface templates have been applied, the command can be changed to: 'show derived-config | section ^interface'

###### EXAMPLE

> show running-config | section ^interface

switch201#show running-config | section ^interface
interface GigabitEthernet1/0/1
no logging event link-status
no cdp enable
no snmp trap link-status
source template ENDUSER_WORKSTATION
service-policy input PM_IN_MARKING

> show derived-config | section ^interface

switch01#show derived-config | section ^interface
interface GigabitEthernet1/0/1
description Workstation_###_MDX
switchport access vlan 780
switchport mode access
no logging event link-status
load-interval 30
no cdp enable
no snmp trap link-status
spanning-tree portfast
service-policy input PM_IN_MARKING

**Comment by KB-perByte** [comment]
Hey, @ljankok with the reported request there are a set of problems that don't make it the right choice to change the command from running-config to derived-config. 
1. while a config is coming from the template's config there is no way to negate/modify it from the scope of the interface itself, which impacts the way resource modules work with action states in consideration.
2. a change in the template impacts every interface using that template, which moves the control away from the resource module.
3. templates are not specific to the resource l2_interfaces so it is not the right scope to consider within the module.

It is encouraged to use Ansible's templating features to achieve similar use-cases. And for using on box templating features cli_parse or the ios_config modules are always there.
With the state parsed, the output of `show derived-config | section ^interface` can be converted to a source of truth, and the module can be used normally.
Regards

**Comment by KB-perByte** [comment]
Hey @ljankok, a recommended workaround for using the module would be as per the following steps,
1. use `show derived-config | section ^interface` to collect the configuration flowing in from the template.
2. use `parsed` state with the collected config from _step 1_ and verify the correct configuration is parsed for the `l2_interfaces` module.
3. use the `ios_config` module to negate the `source template` commands from available interfaces.
4. use state `overridden/replaced` to push back the source of truth verified in _step 2_, using the `l2_interfaces` resource module.
Once the source template commands are negated and the configuration is applied _not via on box template_, the expected configuration would be parsed correctly in the facts with the `show running-config | section ^interface`'s commands scope which is considered in the module.

Regards
