### ISSUE TITLE
Modules only execute with manual input when tunneling to serial console

### ISSUE THREAD

**Issue by felixblang** [ansible-collections/cisco.ios#523]
##### SUMMARY

I'm using an opengear console server to create an out of band access to my switches.
this allows me to open an ssh session to the console server which gets forewarded to the serial port.
When i execute Modules through this connection the task runns into a timeout as it waits for the switch to show something upon successful connection. If i manually enter something on the switch, which triggers a new line the ansible task starts running.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_config

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6]
python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
jinja version = 3.0.2
```

##### COLLECTION VERSION

```paste below
cisco.ios  2.5.0
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco IOS XE Software, Version 16.12.05b

##### STEPS TO REPRODUCE

use an opengear console server to foreward an ssh session to a serial port in the format
```
ssh ansible@opengear.server -p 3001
```
to connect to the switch on serial port 1 and execute any playbook using this connection.

```yaml
cisco.ios.ios_config: 
    backup_options:
      dir_path: "{{ localpath.path }}"
      filename: "{{ inventory_hostname }}.cfg"
    backup: true
```

##### EXPECTED RESULTS

the playbook creates a backup of the running config and saves it to the provided location

##### ACTUAL RESULTS

the task only executes successfully if i press 'enter', CTRL+C or CTRL+Z on the serial console, to prompt a new line on the switch while the task is active.

```paste below
TASK [backupconfig : BACKUP RUNNING-CONFIG IOS] ***************************************************************************************************
fatal: [C3650-2]: FAILED! => {"changed": false, "msg": "command timeout triggered, timeout value is 30 secs.
See the timeout setting options inteN the Network Debug and Troubleshooting Guide."}
```

**Comment by KB-perByte** [comment]
Hey @felixblang, does your inventory have the correct port information to connect?

**Comment by felixblang** [comment]
Yes, all the connection info works. As I said it stops on the task and if I input something manually it runs the task, so the connection definitely works

**Comment by KB-perByte** [comment]
So @felixblang, if you enter something on the device it works without a timeout? I am unable to reproduce the same at my end.

**Comment by felixblang** [comment]
@KB-perByte yes, from what i can tell ansible is not getting feedback for a successfull connection until i enter something manually. Once i do that i can see it starting to execute commands on the switch

**Comment by felixblang** [comment]
@KB-perByte, I have narrowed it down as far as i could and the problem seems to be that ansible.netcommon.network_cli always expects an initial_prompt for a connection. I have experimented with the ansible_terminal_initial_prompt variable but it doesn't seem to have any way for me to set it to 'no prompt'

should i close this issue and move to https://github.com/ansible-collections/ansible.netcommon/issues ?
