### ISSUE TITLE
"No existing session" in CI

### ISSUE THREAD

**Issue by goneri** [ansible-collections/cisco.ios#542]
Hi,

The paramiko based integration tests fail with the message from Topic.

e.g: https://dashboard.zuul.ansible.com/t/ansible/build/21835f8df8db4d6ea375ec8fb8c7132d/logs

**Comment by KB-perByte** [comment]
Closing this off, on the discussion that it is a paramiko issue where multiple keys are involved it fails to try it with the correct keys and fails.
