### ISSUE TITLE
Please add support for specifying syslog port number and transport type in the ios_logging module

### ISSUE THREAD

**Issue by erictomb** [ansible-collections/cisco.ios#57]
SUMMARY
The ios_logging module does not support configuring logging on Cisco IOS to non standard syslog ports. Standard port is UDP 514, but some log collectors listen on different ports.

ISSUE TYPE
Feature Idea
Create a transport parameter so that users can specify sending syslog messages to different ports. I would like to see it support the following command:
logging host 1.2.3.4 transport udp port 1234
On Cisco devices, tcp transport is also supported. I'd like to see that as well.
COMPONENT NAME
This should be supported in the ios_logging module.

ADDITIONAL INFORMATION
There are services such as Sumologic that collect logs from an organization and keep them in the cloud. Internally there are collectors that devices point their logs to and in turn are redirected to Sumologic. Different port numbers are sometimes used to distinguish different types of devices. For example, firewalls might log to port 11111, routers to port 22222, etc.

Command would be: logging host 1.2.3.4 transport udp port 1234

it could look like this in the yaml file:

- name:
  ios_logging:
    - dest: host
    - name: 1.2.3.4
    - transport: udp
    - port: 1234
    - state: present

I opened this issue in a different repository and was asked to resubmit this request here by maintainer danielmellado.
https://github.com/ansible/ansible/issues/67314#issuecomment-632688869

**Comment by erictomb** [comment]
Any updates on this issue?  Has anyone looked at this yet?

**Comment by justjais** [comment]
@erictomb excuse me for the super delayed response, you can expect me to triage the issue, and if there's a fix needed you can expect the same in February'21.

**Comment by erictomb** [comment]
@justjais I just saw this message and am wondering whether you were able to add a fix.  Thanks for getting back to me.

**Comment by justjais** [comment]
@erictomb not yet, but you can expect the update during upcoming week.
