### ISSUE TITLE
no serial console connection support - why?

### ISSUE THREAD

**Issue by 0xdd7fq** [ansible-collections/cisco.ios#583]
For example I have 100 switches and I have no time configure ip addressing and ssh on all devices

**Comment by KB-perByte** [comment]
Hey @0xdd7fq we don't have support for serial connection for some very specific reasons
1. Serial connection is local and physical we are not able to access the devices placed elsewhere to manage its configuration.
2. Ansible is not specifically there for bootstrapping devices it is more for configuration management.
both the points explain why the serial connection is not the right choice for Ansible.
Regards
