### ISSUE TITLE
Support IPv6 Ping

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.ios#584]
SUMMARY
Support pinging IPv6 devices

ISSUE TYPE
Feature Idea, Feature Request
COMPONENT NAME
cisco.ios.ios_ping

ADDITIONAL INFORMATION
Used to ping remote devices via module instead of using an xxxx_command module to send a raw command and having to parse and modify return data

(IPv6 support should be standard across all network modules)

**Comment by KB-perByte** [comment]
Hey @digitalfiend64, it is in our roadmap the feature is to be available soon.

**Comment by digitalfiend64** [comment]
> Hey @digitalfiend64, it is in our roadmap the feature is to be available soon.

Thank you KB.  I would like to pass on more information to the customer about our plans for this feature, primarily timing.  Do we have an estimated date or a target release that this feature is intended for?  Is there an existing issue that I should link to instead of this one?

**Comment by KB-perByte** [comment]
Hey @digitalfiend64, We are updating all our supported platforms to support ipv6 ping, it will be implemented in IOS by the next month's release, I'll update the progress here.
Regards

**Comment by digitalfiend64** [comment]
Hi KB, what's the current status on this?  :-)

**Comment by KB-perByte** [comment]
Hey @digitalfiend64, the PR is merged and will be released with this month's release, which got delayed because of some CI issues. It will be released by 4th July.
Regards

**Comment by digitalfiend64** [comment]
Hi KB,
  Unless I'm overlooking something, I'm not seeing this merged into the main branch.  Is it merged in and available in a specific release version that I'm just overlooking?

**Comment by KB-perByte** [comment]
Hey @aenglmeier,
Can you please help me with the netcommon and cisco.ios collection version,
And please note the default [value](https://github.com/ansible-collections/cisco.ios/blob/main/docs/cisco.ios.ios_ping_module.rst#parameters) for afi is ip not ipv4.
And for my better understanding would you be able to share the output of the following playbook with any ipv6 address :
```
    - name: Test ipv6 ping
      ansible.netcommon.net_ping:
        dest: {{ ipv6_address }}
        afi: ipv6
```
and yes, Please consider creating a new issue for me to track it better.
Regards

**Comment by KB-perByte** [comment]
@aenglmeier the afi parameter is only valid for cisco ios and iosxr. The idea that you shared is valid. Let me check if there is a quick workaround. And thanks for pointing it out, I would enhance the documentation too!
Regards
