### ISSUE TITLE
Getting Traceback Fatal from ios.py and connection.py

### ISSUE THREAD

**Issue by andysmagana** [ansible-collections/cisco.ios#589]
Ansible Tower project playbook is simple just go to Cisco CIMC C240 M5 and get snmp information. The traceback is from ios.py and connection.py utilizing the ios_command module. I am tired and can't figure out why !

Playbook works on other C240's but not two of them.

Playbook

```
  ```
  ---
    - name: Get snmp information
      hosts: cimc
      connection: network_cli
      gather_facts: false
       
      tasks: 
       - name: get snmp engineID
         ios_command: 
           commands: show snmp
         register: show_engineID
```



    The full traceback is:
     File "tmp/ansible_ios_command_payloadjo4_2mga/ansible_ios_command_payload.zip/ansible/module_utils/network/ios/ios.py", line 86, in get_capabilities 
      capabilities = Connection(module._socket_path).get_capabilities()
     File "tmp/ansible_ios_command_payloadjo4_2mga/ansible_ios_command_payload.zip/ansible/module_utils/connection.py", line 185, in _rpc_
      raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
    fatal: [mycimc240.local.example]: FAILED! =>
      "ansible facts":
      },"discovered_interpreter_python": "/usr/libexec/platform-python"
      "changed": false,
      "invocation": 1
        "module_args": I
          "auth_pass": null, 
          "authorize": null, 
          "commands": [
            "show snmp detail 1 grep \"Engine RA"
          ],
          "host": null,
          "interval": 1,
          "match": "all", 
          "password": null, 
          "port": null,
          "provider": null, 
          "retries": 10,
          "ssh_keyfile": null, 
          "timeout": null, 
          "username": null, 
        } "wait for": null
      },
```

**Comment by KB-perByte** [comment]
Hey @andysmagana Looks like Ansible was unable to understand the prompt the device returned when the command was fired.
Is Cisco CIMC C240 M5 an IOS device? Can you please confirm?
Regards

**Comment by KB-perByte** [comment]
Closing the issue as the conversation is inactive, please reopen an issue if the problem persists.
Regards
