### ISSUE TITLE
Vlan facts fails with "list index out of range"

### ISSUE THREAD

**Issue by TheUltimateDeployer** [ansible-collections/cisco.ios#596]
##### SUMMARY
The retrieval of facts fails with an "list index out of range" error in the vlan.py file (/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 177, in render_config)
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module_utils

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = None
  configured module search path = ['/home/chris/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, Nov 18 2021, 16:00:48) [GCC 10.3.0]

```

##### COLLECTION VERSION

```paste below

# /home/chris/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  3.1.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  1.3.0  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Software
  BIOS: version 07.34
  NXOS: version 7.0(3)I2(5)
  BIOS compile time:  08/11/2015
  NXOS image file is: bootflash:///nxos.7.0.3.I2.5.bin
  NXOS compile time:  1/13/2017 7:00:00 [01/13/2017 16:42:44]

Hardware
  cisco Nexus9000 C9372PX chassis 
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16401960 kB of memory.
  Processor Board ID SAL1930L125

##### STEPS TO REPRODUCE

All tasks are affected which require the gathering of facts

```yaml

```

##### ACTUAL RESULTS

I gathered the actual values of the conf list by raising an exception:
['1', 'enet', 'CE']
The length of the list is in our case 3.
A simple check for the length is fixing this problem:
            if len(conf) > 3:
                config["mtu"] = int(conf[3])

```paste below
The full traceback is:
  File "/home/chris/.ansible/collections/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 133, in get_network_resources_facts
    inst.populate_facts(
  File "/home/chris/.ansible/collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 101, in populate_facts
    obj = self.render_config(self.generated_spec, conf, vlan_info)
  File "/home/chris/.ansible/collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 177, in render_config
    config["mtu"] = int(conf[3])
fatal: [ipz-zbl1644-s-hr-50]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "mtu": null,
                    "name": "Vlan__0",
                    "remote_span": true,
                    "shutdown": "enabled",
                    "state": "active",
                    "vlan_id": 1001
                },
                {
                    "mtu": null,
                    "name": "Vlan__1",
                    "remote_span": true,
                    "shutdown": "enabled",
                    "state": "active",
                    "vlan_id": 1002
                },
                {
                    "mtu": null,
                    "name": "Vlan_2",
                    "remote_span": true,
                    "shutdown": "enabled",
                    "state": "active",
                    "vlan_id": 1003
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "msg": "list index out of range"
}

```

**Comment by KB-perByte** [comment]
Hey, @TheUltimateDeployer I see you are using a Nexus chassis, you must check the same with https://github.com/ansible-collections/cisco.nxos/blob/main/docs/cisco.nxos.nxos_vlans_module.rst in your case. If the issue persists please report it in
 https://github.com/ansible-collections/cisco.nxos/issues
Regards

**Comment by TheUltimateDeployer** [comment]
Thanks for the hint. It worked.

Thanks you!
