### ISSUE TITLE
IOS_VRF Module *Sending Wrong Commands For VRF Creation?*

### ISSUE THREAD

**Issue by MrSteve81** [ansible-collections/cisco.ios#599]
##### SUMMARY

Upon working with the vrf module I keep running into a number of errors trying to create new VRF on my Cisco devices.  I kept receiving the following error.      "msg": "vrf definition test2\r\nvrf definition test2\r\n ^\r\n% Invalid input detected at '^' marker.\r\n\r\nPE-ROUTER-2(config)#" Using Check mode  

It seems as if the module is firing the wrong commands from the python core.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_vrf

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.1]
  config file = /Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg
  configured module search path = ['/Users/stephenw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.0.1/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/stephenw/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.1 (main, Dec  6 2021, 23:20:29) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /Users/stephenw/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  2.7.2  

# /usr/local/Cellar/ansible/5.0.1/libexec/lib/python3.10/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.5.0  
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg) = ['/Users/step
HOST_KEY_CHECKING(/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Cisco IOS Software, 3700 Software (C3725-ADVENTERPRISEK9-M), Version 12.4(15)T14

##### STEPS TO REPRODUCE

Create any role using the vrf module and try to use any option.  

```yaml
    - name: "Create VRF Entries"
      ios_vrf:
        name: test2
        state: present
      check_mode: yes```
```

##### EXPECTED RESULTS

Creation of a new vrf on the system using the command 
`ip vrf test2`

##### ACTUAL RESULTS

Command fails because it is using the wrong syntax to create the vrf on the Cisco module.  If  I run the play with check mode in it it of course shows changed but the commands it shows is what is I caught that I know is the issue.  

```paste below
changed: [192.168.1.42] => {
    "changed": true,
    "commands": [
        "vrf definition test2"

The full traceback is:
  File "/var/folders/jx/s1c_kbp95qsc0844d9l97rx40000gq/T/ansible_ios_vrf_payload_b1u943yz/ansible_ios_vrf_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 150, in load_config
    resp = connection.edit_config(commands)
  File "/var/folders/jx/s1c_kbp95qsc0844d9l97rx40000gq/T/ansible_ios_vrf_payload_b1u943yz/ansible_ios_vrf_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [192.168.1.42]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "associated_interfaces": null,
            "delay": 10,
            "description": null,
            "interfaces": null,
            "name": "test2",
            "provider": null,
            "purge": false,
            "rd": null,
            "route_both": null,
            "route_both_ipv4": null,
            "route_both_ipv6": null,
            "route_export": null,
            "route_export_ipv4": null,
            "route_export_ipv6": null,
            "route_import": null,
            "route_import_ipv4": null,
            "route_import_ipv6": null,
            "state": "present",
            "vrfs": null
        }
    },
    "msg": "vrf definition test2\r\nvrf definition test2\r\n ^\r\n% Invalid input detected at '^' marker.\r\n\r\nPE-ROUTER-2(config)#"
}
```

**Comment by KB-perByte** [comment]
hey @MrSteve81, 
the latest supported IOS version for this collection is 15.6 and we would be soon updating it to 17.x,
the VRF command fired from the module is `vrf definition test2` which was supported in version 15, the correct supported format is `ip vrf test2`. I would raise a PR to fix the same.
Regards

**Comment by KB-perByte** [comment]
Hey @MrSteve81 Thanks for sharing the details, I would keep the issue open for some time as we are planning for an IOS-supported version update from 15.x to 17.x which would need some change in the modules across the collection. The issue would be addressed with that change as 17.x will not have support for `vrf definition test2` command it would need the ip command to be fired.
Regards

**Comment by KB-perByte** [comment]
@MrSteve81 I wanted to update you on the status of this issue, 
from version 16+ I see a warning to use the definition command instead of the IP command, even the docs confirm the same.
we won't be making the reported changes as they were valid for IOS version 12. The upcoming supported version for the collection would be IOSXE 17+
```
R1(config)#do show ver
Cisco IOS XE Software, Version 17.03.04a

R1(config)#ip vrf test_vrf_a
% Use 'vrf definition test_vrf_a' command
```
Closing the issue, please feel free to raise a fresh issue if needed.
Regards

**Comment by bentole** [comment]
Hi guys! I know this issue's closed, but I'd like to add a bit of information regarding this. To sum up; `vrf definition` was introduced as a replacement for `ip vrf` to make vrf configurations "protocol agnostic" (in lack of a better term 😄 ). In other words; to support both ipv4 and ipv6.

For those of you "stuck" with `ip vrf` configurations, I'd like to remind you that there's a command that will automatically migrate to the new syntax: 

`vrf upgrade-cli multi-af-mode non-common-policies`

Common or non-common policies is up to anyone to decide for themselves. That's a discussion for another forum 😄 

Hope this helps anyone!
