### ISSUE TITLE
l2_interfaces of gather_network_resources in cisco.ios.ios_facts fails with msg:'value of vlan_tag must be one of: dot1p, none, untagged, got: 70 found in config -> voice'

### ISSUE THREAD

**Issue by boomsfib** [ansible-collections/cisco.ios#643]
##### SUMMARY

When running 

cisco.ios.ios_facts:
  gather_network_resources:
  - l2_interfaces
  
I now get the following error: "msg: 'value of vlan_tag must be one of: dot1p, none, untagged, got: 70 found in config -> voice'".  I noticed this started failing in version 3.2.  It is failing in version 3.3 as well.  Worked in version 3.0.  I do not know if it worked in version 3.1

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

l2_interfaces of gather_network_resources within cisco.ios.ios_facts

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.2]
  config file = /usr/devnet/cisco_config_mgmt/ansible.cfg
  configured module search path = ['/home/mjbright/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mjbright/projects/cisco_config_mgmt/.venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/mjbright/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mjbright/projects/cisco_config_mgmt/.venv/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
(.venv) mjbright@labdevnet:~/devnet/cisco_config_mgmt$ ansible-galaxy collection list cisco.ios

# /home/mjbright/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  3.3.0  

# /home/mjbright/projects/cisco_config_mgmt/.venv/lib/python3.8/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  3.2.0 
```

##### CONFIGURATION

```paste below
(.venv) mjbright@labdevnet:~/devnet/cisco_config_mgmt$ ansible-config dump --only-changed
CALLBACKS_ENABLED(/usr/devnet/cisco_config_mgmt/ansible.cfg) = ['profile_tasks', 'timer', 'mail', 'profile_roles', 'log_plays']
COLOR_DIFF_ADD(/usr/devnet/cisco_config_mgmt/ansible.cfg) = bright magenta
DEFAULT_FILTER_PLUGIN_PATH(/usr/devnet/cisco_config_mgmt/ansible.cfg) = ['/usr/devnet/cisco_config_mgmt/filter_plugins']
DEFAULT_FORKS(/usr/devnet/cisco_config_mgmt/ansible.cfg) = 20
DEFAULT_GATHERING(/usr/devnet/cisco_config_mgmt/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/usr/devnet/cisco_config_mgmt/ansible.cfg) = ['/usr/devnet/cisco_config_mgmt/inventory/hosts.yml']
DEFAULT_LOG_PATH(/usr/devnet/cisco_config_mgmt/ansible.cfg) = /usr/devnet/log/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/usr/devnet/cisco_config_mgmt/ansible.cfg) = ['/usr/devnet/cisco_config_mgmt/plugins/lookup']
DEFAULT_STDOUT_CALLBACK(/usr/devnet/cisco_config_mgmt/ansible.cfg) = yaml
DEPRECATION_WARNINGS(/usr/devnet/cisco_config_mgmt/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/usr/devnet/cisco_config_mgmt/ansible.cfg) = False
HOST_KEY_CHECKING(/usr/devnet/cisco_config_mgmt/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/usr/devnet/cisco_config_mgmt/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/usr/devnet/cisco_config_mgmt/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/usr/devnet/cisco_config_mgmt/ansible.cfg) = 60
RETRY_FILES_ENABLED(/usr/devnet/cisco_config_mgmt/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco IOS XE Software, Version 17.03.05
Cisco IOS Software [Amsterdam], Catalyst L3 Switch Software (CAT9K_LITE_IOSXE), Version 17.3.5, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2022 by Cisco Systems, Inc.
Compiled Wed 09-Feb-22 09:28 by mcpre

Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(7)E4, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2021 by Cisco Systems, Inc.
Compiled Mon 08-Mar-21 11:26 by prod_rel_team

##### STEPS TO REPRODUCE

```yaml
---
- name: Playbook to Test IOS Facts
  hosts: Lab_CiscoSiteB_Sw1
  connection: network_cli
  gather_facts: False
  vars_files:
    - secret.yml

  tasks:
    - name: Retrieve Interface Information from Device
      cisco.ios.ios_facts:
        gather_network_resources: 
        - l2_interfaces
```

##### EXPECTED RESULTS

In cisco.ios version 3.0 the results were as follows

"l2_interfaces": [
                {
                    "name": "Port-channel2",
                    "mode": "trunk",
                    "trunk": {
                        "native_vlan": 3
                    }
                },
                {
                    "name": "FastEthernet0"
                },
                {
                    "name": "GigabitEthernet1/0/1",
                    "mode": "access",
                    "access": {
                        "vlan": 666
                    },
                    "voice": {
                        "vlan": 70
                    }
                },
                {
                    "name": "GigabitEthernet1/0/2",
                    "mode": "access",
                    "access": {
                        "vlan": 666
                    },
                    "voice": {
                        "vlan": 70
                    }
                }

##### ACTUAL RESULTS

Starting with cisco.ios version 3.2, the results look like this and we get the mentioned error.

{
    "msg": "value of vlan_tag must be one of: dot1p, none, untagged, got: 70 found in config -> voice",
    "invocation": {
        "module_args": {
            "config": [
                {
                    "name": "FastEthernet0",
                    "mode": null,
                    "access": null,
                    "voice": null,
                    "trunk": null
                },
                {
                    "name": "GigabitEthernet1/0/1",
                    "mode": "access",
                    "access": {
                        "vlan": 666,
                        "vlan_name": null
                    },
                    "voice": {
                        "vlan_tag": "70",
                        "vlan": null,
                        "vlan_name": null
                    },
                    "trunk": null
                },
                {
                    "name": "GigabitEthernet1/0/2",
                    "mode": "access",
                    "access": {
                        "vlan": 666,
                        "vlan_name": null
                    },
                    "voice": {
                        "vlan_tag": "70",
                        "vlan": null,
                        "vlan_name": null
                    },
                    "trunk": null
                }

```paste below

```

**Comment by KB-perByte** [comment]
Hey @boomsfib,
we added the vlan_tag option with 3.2, must be a bug related to that
could you please share the output of `show running-config | section ^interface` so that I can be sure, I am pushing a Fix and tagging the PR here for you to check against?
Regards

**Comment by boomsfib** [comment]
Hey @KB-perByte ,

Here is a running config for one of our interfaces.  

```
interface GigabitEthernet1/0/1
 switchport access vlan 666
 switchport mode access
 switchport block unicast
 switchport voice vlan 70
 srr-queue bandwidth share 1 30 35 5
 priority-queue out
 authentication control-direction in
 authentication event fail action next-method
 authentication event server dead action authorize voice
 authentication event no-response action authorize vlan 43
 authentication event server alive action reinitialize
 authentication host-mode multi-auth
 authentication open
 authentication order dot1x mab
 authentication priority dot1x mab
 authentication port-control auto
 authentication periodic
 authentication timer reauthenticate server
 authentication violation restrict
 mab
 snmp trap mac-notification change added
 snmp trap mac-notification change removed
 mls qos trust dscp
 macro description DOT1X-PORT-FULL
 dot1x pae authenticator
 dot1x timeout tx-period 4
 spanning-tree portfast edge
 spanning-tree bpduguard enable
```

**Comment by KB-perByte** [comment]
@boomsfib thanks for the details this https://github.com/ansible-collections/cisco.ios/pull/644 should solve the issue.
Regards

**Comment by boomsfib** [comment]
@KB-perByte thank you sir.  is anything else needed from me?

**Comment by KB-perByte** [comment]
@boomsfib nope, Thanks for the help

**Comment by tgraham2** [comment]
I get the same thing. Was this issue closed?

interface GigabitEthernet0/3
 switchport access vlan 555
 switchport mode access
 switchport voice vlan 755
 no logging event link-status


FAILED! => {"changed": false, "msg": "value of vlan_tag must be one of: dot1p, none, untagged, got: 755 found in config -> voice"}

**Comment by KB-perByte** [comment]
@tgraham2 It is yet to be merged and released!
