### ISSUE TITLE
cisco.ios.ios_logging_global_module transport tls support

### ISSUE THREAD

**Issue by regold666** [ansible-collections/cisco.ios#648]
##### SUMMARY

Support for transport protocol tls is missing in module

##### ISSUE TYPE
- Feature Idea
add support for transport protocol tls 

##### COMPONENT NAME

cisco.ios.ios_logging_global module

##### ADDITIONAL INFORMATION

secure logging is an Importen and requested feature. secure logging is an available feature on cisco devices  but is not supported by cisco.ios.ios_logging_global
  

```yaml

```

**Comment by KB-perByte** [comment]
Hey @regold666 is this about the tls-profile attribute under logging configuration?
Would you share a config snippet of the configuration you are looking for?
Regards

**Comment by KB-perByte** [comment]
Closing as the issue is inactive, please open a new issue if the problem persists.
Regards
