### ISSUE TITLE
Error when attempting to remove config from an interface that doesn't have the config

### ISSUE THREAD

**Issue by ejohn167** [ansible-collections/cisco.ios#651]
##### SUMMARY
When trying to remove configuration from interfaces, if one interface doesn't contain the configuration, the following interfaces all fail  with show version as the offending input.

 no switchport port-security\r\nno switchport port-security\r\n               ^\r\n% Invalid input detected at '^' marker.\r\n\r\n0164H-IDFEN-ASW-01(config-if)#\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
failed: [0164H-IDFEN-ASW-01] (item={u'key': u'GigabitEthernet4/0/33', u'value': {u'macaddress': u'00a2.ee87.9721', u'lineprotocol': None, u'description': None, u'duplex': None, u'mediatype': u'10/100/1000BaseTX', u'mtu': 1500, u'operstatus': u'down', u'bandwidth': 1000000, u'ipv4': [], u'type': u'Gigabit Ethernet'}}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "GigabitEthernet4/0/33", "value": {"bandwidth": 1000000, "description": null, "duplex": null, "ipv4": [], "lineprotocol": null, "macaddress": "00a2.ee87.9721", "mediatype": "10/100/1000BaseTX", "mtu": 1500, "operstatus": "down", "type": "Gigabit Ethernet"}}, "msg": "show version\r\nshow version\r\n  ^\r\n% Invalid input detected at '^' marker.\r\n\r\n0164H-IDFEN-ASW-01(config-if)#"}

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 28 2022, 15:30:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

```

##### COLLECTION VERSION

```paste below
3.3.0
```

##### CONFIGURATION

```paste below
:/data/ansible/playbooks # ansible-config dump --only-changed
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/data/ansible/inventory']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/data/ansible']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 180
```

##### OS / ENVIRONMENT

Centos 7

##### STEPS TO REPRODUCE

On a Cisco switch run the playbook against all interfaces.

On one interface, have default config - it should fail, or if an interface is a trunk port

```yaml
hosts: all
gather_facts: yes

tasks:
  - name: remove service policies
    ios_config:
      lines:
        - no switchport port-security
        - no storm-control broadcast level
        - no storm-control multicast level
        - no storm-control action shutdown
        - no switchport port-security maximum
        - no switchport port-security maximum 2 vlan access
        - no switchport port-security violation
        - no switchport port-security aging time
        - no switchport port-security aging type
        - no ip dhcp snooping limit rate
        - no ip dhcp snooping trust
        - no service-policy input AutoQos-4.0-Trust-Cos-Input-Policy
        - no service-policy output AutoQos-4.0-Output-Policy
      parents: "interface {{ item.key }}"
    with_dict: "{{ ansible_net_interfaces }}"
    when: item.key == "Gigabit Ethernet" or item.value.type == "Fast Ethernet"

  - name: save config
    ios_config:
      save_when: always
```

##### EXPECTED RESULTS

Expectation is to execute the configuration changes and if one interface fails, continue through the rest of the interfaces.

##### ACTUAL RESULTS

```paste below
changed: [HOSTNAME] => (item={u'key': u'GigabitEthernet4/0/32', u'value': {u'macaddress': u'00a2.ee87.9720', u'lineprotocol': None, u'description': None, u'duplex': None, u'mediatype': u'10/100/1000BaseTX', u'mtu': 1500, u'operstatus': u'down', u'bandwidth': 1000000, u'ipv4': [], u'type': u'Gigabit Ethernet'}}) => {
    "ansible_loop_var": "item",
    "banners": {},
    "changed": true,
    "commands": [
        "interface GigabitEthernet4/0/32",
        "no switchport port-security",
        "no storm-control broadcast level",
        "no storm-control multicast level",
        "no storm-control action shutdown",
        "no switchport port-security maximum",
        "no switchport port-security maximum 2 vlan access",
        "no switchport port-security violation",
        "no switchport port-security aging time",
        "no switchport port-security aging type",
        "no ip dhcp snooping limit rate",
        "no ip dhcp snooping trust",
        "no service-policy input AutoQos-4.0-Trust-Cos-Input-Policy",
        "no service-policy output AutoQos-4.0-Output-Policy"
    ],
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "host": null,
            "intended_config": null,
            "lines": [
                "no switchport port-security",
                "no storm-control broadcast level",
                "no storm-control multicast level",
                "no storm-control action shutdown",
                "no switchport port-security maximum",
                "no switchport port-security maximum 2 vlan access",
                "no switchport port-security violation",
                "no switchport port-security aging time",
                "no switchport port-security aging type",
                "no ip dhcp snooping limit rate",
                "no ip dhcp snooping trust",
                "no service-policy input AutoQos-4.0-Trust-Cos-Input-Policy",
                "no service-policy output AutoQos-4.0-Output-Policy"
            ],
            "match": "line",
            "multiline_delimiter": "@",
            "parents": [
                "interface GigabitEthernet4/0/32"
            ],
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "running_config": null,
            "save_when": "never",
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "item": {
        "key": "GigabitEthernet4/0/32",
        "value": {
            "bandwidth": 1000000,
            "description": null,
            "duplex": null,
            "ipv4": [],
            "lineprotocol": null,
            "macaddress": "00a2.ee87.9720",
            "mediatype": "10/100/1000BaseTX",
            "mtu": 1500,
            "operstatus": "down",
            "type": "Gigabit Ethernet"
        }
    },
    "updates": [
        "interface GigabitEthernet4/0/32",
        "no switchport port-security",
        "no storm-control broadcast level",
        "no storm-control multicast level",
        "no storm-control action shutdown",
        "no switchport port-security maximum",
        "no switchport port-security maximum 2 vlan access",
        "no switchport port-security violation",
        "no switchport port-security aging time",
        "no switchport port-security aging type",
        "no ip dhcp snooping limit rate",
        "no ip dhcp snooping trust",
        "no service-policy input AutoQos-4.0-Trust-Cos-Input-Policy",
        "no service-policy output AutoQos-4.0-Output-Policy"
    ]
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/ios/ios_config.py
<10.41.13.160> PUT /root/.ansible/tmp/ansible-local-27826YaVRC5/tmpM8G6Wu TO /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/AnsiballZ_ios_config.py
<10.41.13.160> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/ /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/AnsiballZ_ios_config.py && sleep 0'
<10.41.13.160> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/AnsiballZ_ios_config.py && sleep 0'
<10.41.13.160> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/ > /dev/null 2>&1 && sleep 0'
<10.41.13.160> Using network group action ios for ios_config
<10.41.13.160> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-27826YaVRC5 `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665549.9-27942-217509946970847 `" && echo ansible-tmp-1662665549.9-27942-217509946970847="` echo /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665549.9-27942-217509946970847 `" ) && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/AnsiballZ_ios_config.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/AnsiballZ_ios_config.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/AnsiballZ_ios_config.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.ios.ios_config', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_ios_config_payload_iYEmWF/ansible_ios_config_payload.zip/ansible/modules/network/ios/ios_config.py", line 569, in <module>
  File "/tmp/ansible_ios_config_payload_iYEmWF/ansible_ios_config_payload.zip/ansible/modules/network/ios/ios_config.py", line 500, in main
  File "/tmp/ansible_ios_config_payload_iYEmWF/ansible_ios_config_payload.zip/ansible/modules/network/ios/ios_config.py", line 364, in edit_config_or_macro
  File "/tmp/ansible_ios_config_payload_iYEmWF/ansible_ios_config_payload.zip/ansible/module_utils/connection.py", line 190, in __rpc__
ansible.module_utils.connection.ConnectionError: no switchport port-security
no switchport port-security
               ^
% Invalid input detected at '^' marker.

HOSTNAME(config-if)#
failed: [0164H-IDFEN-ASW-01] (item={u'key': u'GigabitEthernet1/1/1', u'value': {u'macaddress': u'00a2.ee87.71b1', u'lineprotocol': None, u'description': u'-> 0164H-MDF-CRT-01, E1/10', u'duplex': None, u'mediatype': u'1000BaseSX SFP', u'mtu': 1500, u'operstatus': u'up', u'bandwidth': 1000000, u'ipv4': [], u'type': u'Gigabit Ethernet'}}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "key": "GigabitEthernet1/1/1",
        "value": {
            "bandwidth": 1000000,
            "description": "-> 0164H-MDF-CRT-01, E1/10",
            "duplex": null,
            "ipv4": [],
            "lineprotocol": null,
            "macaddress": "00a2.ee87.71b1",
            "mediatype": "1000BaseSX SFP",
            "mtu": 1500,
            "operstatus": "up",
            "type": "Gigabit Ethernet"
        }
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/AnsiballZ_ios_config.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/AnsiballZ_ios_config.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665546.21-27942-105217022507565/AnsiballZ_ios_config.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.ios.ios_config', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_ios_config_payload_iYEmWF/ansible_ios_config_payload.zip/ansible/modules/network/ios/ios_config.py\", line 569, in <module>\n  File \"/tmp/ansible_ios_config_payload_iYEmWF/ansible_ios_config_payload.zip/ansible/modules/network/ios/ios_config.py\", line 500, in main\n  File \"/tmp/ansible_ios_config_payload_iYEmWF/ansible_ios_config_payload.zip/ansible/modules/network/ios/ios_config.py\", line 364, in edit_config_or_macro\n  File \"/tmp/ansible_ios_config_payload_iYEmWF/ansible_ios_config_payload.zip/ansible/module_utils/connection.py\", line 190, in __rpc__\nansible.module_utils.connection.ConnectionError: no switchport port-security\r\nno switchport port-security\r\n               ^\r\n% Invalid input detected at '^' marker.\r\n\r\n0164H-IDFEN-ASW-01(config-if)#\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/ios/ios_config.py
<10.41.13.160> PUT /root/.ansible/tmp/ansible-local-27826YaVRC5/tmpRBrU1q TO /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665549.9-27942-217509946970847/AnsiballZ_ios_config.py
<10.41.13.160> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665549.9-27942-217509946970847/ /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665549.9-27942-217509946970847/AnsiballZ_ios_config.py && sleep 0'
<10.41.13.160> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665549.9-27942-217509946970847/AnsiballZ_ios_config.py && sleep 0'
<10.41.13.160> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-27826YaVRC5/ansible-tmp-1662665549.9-27942-217509946970847/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ios_config_payload_jE9NNS/ansible_ios_config_payload.zip/ansible/module_utils/network/ios/ios.py", line 86, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/tmp/ansible_ios_config_payload_jE9NNS/ansible_ios_config_payload.zip/ansible/module_utils/connection.py", line 190, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
failed: [0164H-IDFEN-ASW-01] (item={u'key': u'GigabitEthernet4/0/33', u'value': {u'macaddress': u'00a2.ee87.9721', u'lineprotocol': None, u'description': None, u'duplex': None, u'mediatype': u'10/100/1000BaseTX', u'mtu': 1500, u'operstatus': u'down', u'bandwidth': 1000000, u'ipv4': [], u'type': u'Gigabit Ethernet'}}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "host": null,
            "intended_config": null,
            "lines": [
                "no switchport port-security",
                "no storm-control broadcast level",
                "no storm-control multicast level",
                "no storm-control action shutdown",
                "no switchport port-security maximum",
                "no switchport port-security maximum 2 vlan access",
                "no switchport port-security violation",
                "no switchport port-security aging time",
                "no switchport port-security aging type",
                "no ip dhcp snooping limit rate",
                "no ip dhcp snooping trust",
                "no service-policy input AutoQos-4.0-Trust-Cos-Input-Policy",
                "no service-policy output AutoQos-4.0-Output-Policy"
            ],
            "match": "line",
            "multiline_delimiter": "@",
            "parents": [
                "interface GigabitEthernet4/0/33"
            ],
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "running_config": null,
            "save_when": "never",
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "item": {
        "key": "GigabitEthernet4/0/33",
        "value": {
            "bandwidth": 1000000,
            "description": null,
            "duplex": null,
            "ipv4": [],
            "lineprotocol": null,
            "macaddress": "00a2.ee87.9721",
            "mediatype": "10/100/1000BaseTX",
            "mtu": 1500,
            "operstatus": "down",
            "type": "Gigabit Ethernet"
        }
    },
    "msg": "show version\r\nshow version\r\n  ^\r\n% Invalid input detected at '^' marker.\r\n\r\nHOSTNAME(config-if)#"
```

**Comment by Qalthos** [comment]
The ios_config module tries to run all commands together and in sequence. This is to ensure that potentially dependent config runs only after earlier config, but also for the sake of efficiency. The module has no concept of what exists or can be set on the resource, as it is meant to be able to run commands directly without having to be taught what it means.

Ideally you would use a resource module instead, which _does_ know about these things, but those options don't look like anything we have a resource module for currently. What might work is splitting the commands into logically related groups, and looping through those subsets of config with `ignore_errors: true` set. That way, config relating to switchport can fail, but dhcp snooping config should still try to run.

**Comment by ejohn167** [comment]
Thanks Kate -

I understand your statement in the first line, what I don't understand is
why after one failure, the following errors are showing the error as "show
running-config" rather than the config lines that are listed in the play.

On Wed, Sep 14, 2022 at 8:49 AM Kate Case ***@***.***> wrote:

> The ios_config module tries to run all commands together and in sequence.
> This is to ensure that potentially dependent config runs only after earlier
> config, but also for the sake of efficiency. The module has no concept of
> what exists or can be set on the resource, as it is meant to be able to run
> commands directly without having to be taught what it means.
>
> Ideally you would use a resource module instead, which *does* know about
> these things, but those options don't look like anything we have a resource
> module for currently. What might work is splitting the commands into
> logically related groups, and looping through those subsets of config with ignore_errors:
> true set. That way, config relating to switchport can fail, but dhcp
> snooping config should still try to run.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ansible-2Dcollections_cisco.ios_issues_651-23issuecomment-2D1246793938&d=DwMCaQ&c=WcgfwqEmTvoQFo-2r_imM3-u3PqgcbX26G8vbF-qQsM&r=2ovUXar7CijZHVfuxCtAt2t9rdyxAg54BLLgHx-BuHI&m=7BvLXmpF0XXFuon7Y0GioOPxL1JdFOK0P_df5HodVkAO6MhbbT3vrd3faH-7fYDs&s=fx_vBDYHBO2OT3-05BH4FCn9qSCF6eeByn8mhOhyshU&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A27CFQU66RMCC2L3BS7XNXDV6HJVHANCNFSM6AAAAAAQIDEJDM&d=DwMCaQ&c=WcgfwqEmTvoQFo-2r_imM3-u3PqgcbX26G8vbF-qQsM&r=2ovUXar7CijZHVfuxCtAt2t9rdyxAg54BLLgHx-BuHI&m=7BvLXmpF0XXFuon7Y0GioOPxL1JdFOK0P_df5HodVkAO6MhbbT3vrd3faH-7fYDs&s=75zVXJ8-rFtSXg32eEXdcCIoaq6w3poboKMx0XWkTAk&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 

------
Edward 'Travis' Johnson | Senior Network Engineer | Community Health
Systems | Franklin, Tennessee

**Comment by Qalthos** [comment]
Because the parser detected an error and stopped issuing commands at that point. ios_config has no way of knowing how serious an error it was. Resource-specific modules can and do use some intelligence to ignore non-fatal errors, but ios_config is meant to be usable with any configuration lines, even ones that we haven't encountered before, and so requires a little more work from the user to deal with potential errors. Moreover, it is intended to apply all of the configuration together or fail loudly so you can revert the changes, not to apply some of the config and ask the user to figure it out.

So the ideal solution is to use some detection to apply only config that is valid on the resource either through separate tasks with `when:` clauses, or with a template. Failing that, though, splitting the config into groups that will either succeed or fail together and looping through them will likely get you closer to what you want.

**Comment by ejohn167** [comment]
Yes - that is correct, but shouldn't it move to the next device, and
attempt the configuration?

I understand another interface on the same device failing, but no on the
next device?

On Wed, Sep 14, 2022 at 9:44 AM Kate Case ***@***.***> wrote:

> Because the parser detected an error and stopped issuing commands at that
> point. ios_config has no way of knowing how serious an error it was.
> Resource-specific modules can and do use some intelligence to ignore
> non-fatal errors, but ios_config is meant to be usable with any
> configuration lines, even ones that we haven't encountered before, and so
> requires a little more work from the user to deal with potential errors.
> Moreover, it is intended to apply all of the configuration together or fail
> loudly so you can revert the changes, not to apply some of the config and
> ask the user to figure it out.
>
> So the ideal solution is to use some detection to apply only config that
> is valid on the resource either through separate tasks with when:
> clauses, or with a template. Failing that, though, splitting the config
> into groups that will either succeed or fail together and looping through
> them will likely get you closer to what you want.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ansible-2Dcollections_cisco.ios_issues_651-23issuecomment-2D1246876328&d=DwMCaQ&c=WcgfwqEmTvoQFo-2r_imM3-u3PqgcbX26G8vbF-qQsM&r=2ovUXar7CijZHVfuxCtAt2t9rdyxAg54BLLgHx-BuHI&m=3vyZWUcG_QoFQxIdOh2pLM8tm9DAsVwrJ_CrEmIpNpyZtqMcw02j4bpP2DXOHyHb&s=EE7Knt4zvsNslu5D2SRMfOHDeaRBEDLNI46TUas1UW8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A27CFQTYJMRLDXWBTRMFC3LV6HQFFANCNFSM6AAAAAAQIDEJDM&d=DwMCaQ&c=WcgfwqEmTvoQFo-2r_imM3-u3PqgcbX26G8vbF-qQsM&r=2ovUXar7CijZHVfuxCtAt2t9rdyxAg54BLLgHx-BuHI&m=3vyZWUcG_QoFQxIdOh2pLM8tm9DAsVwrJ_CrEmIpNpyZtqMcw02j4bpP2DXOHyHb&s=B8rrRr_vcEgBcc0JkcXPJL63YRpOP5Y-r13sOYRM620&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 

------
Edward 'Travis' Johnson | Senior Network Engineer | Community Health
Systems | Franklin, Tennessee

**Comment by ejohn167** [comment]
Kate -

You're awesome!  Thank you for the update.



On Thu, Sep 15, 2022 at 9:11 AM Kate Case ***@***.***> wrote:

> Oh I see you are already looping over interfaces as well. This makes your
> output make a lot more sense.
>
> So the issue is that when your task fails, the device is left in config
> mode, and that breaks some of our assumptions. We do check and clear config
> mode between *tasks*, but evidently not between items within a task. #654
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ansible-2Dcollections_cisco.ios_pull_654&d=DwMCaQ&c=WcgfwqEmTvoQFo-2r_imM3-u3PqgcbX26G8vbF-qQsM&r=2ovUXar7CijZHVfuxCtAt2t9rdyxAg54BLLgHx-BuHI&m=TL46HowIj-1tQ5HhcN48ovJ59Ac7Do4T2dw8B81sWiyAt0pNXwWtSn9hicQBw-vS&s=eah8facLf0l3qMCB-E7SmcqEiKrvdThtyEGwO6YiAnI&e=>
> should help with that.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ansible-2Dcollections_cisco.ios_issues_651-23issuecomment-2D1248158693&d=DwMCaQ&c=WcgfwqEmTvoQFo-2r_imM3-u3PqgcbX26G8vbF-qQsM&r=2ovUXar7CijZHVfuxCtAt2t9rdyxAg54BLLgHx-BuHI&m=TL46HowIj-1tQ5HhcN48ovJ59Ac7Do4T2dw8B81sWiyAt0pNXwWtSn9hicQBw-vS&s=jVmhgUW0d3DbN5PVCBfADmXTxCoD33eq0a-tMcd3KVo&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A27CFQV7BTX77HDLLWBMW2LV6MVCZANCNFSM6AAAAAAQIDEJDM&d=DwMCaQ&c=WcgfwqEmTvoQFo-2r_imM3-u3PqgcbX26G8vbF-qQsM&r=2ovUXar7CijZHVfuxCtAt2t9rdyxAg54BLLgHx-BuHI&m=TL46HowIj-1tQ5HhcN48ovJ59Ac7Do4T2dw8B81sWiyAt0pNXwWtSn9hicQBw-vS&s=HbtAwabRzWK9bFKoWzfXFa7nhN1SqXGMMCA5R_M4Pi0&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 

------
Edward 'Travis' Johnson | Senior Network Engineer | Community Health
Systems | Franklin, Tennessee
