### ISSUE TITLE
Please publish release notes

### ISSUE THREAD

**Issue by ledgley** [ansible-collections/cisco.ios#652]
##### SUMMARY
Would it be possible to publish the list of issues closed/resolved/fixed in each release? It would also be useful to understand which modules had changes.

Though this collection has a lot of bugs, we rely on it heavily. We have developed our own workarounds where a module doesn't quite work correctly. Inevitably, as issues are resolved they break some of the workarounds we have in place. It would be helpful to know exactly which modules are being changed in each release, so we can understand any implications of updating the collection version.

Thank you

##### ISSUE TYPE
- Documentation Report

**Comment by Qalthos** [comment]
Release notes are already published [here](https://github.com/ansible-collections/cisco.ios/blob/main/CHANGELOG.rst) as they have been for the entire life of the collection. They are linked to from the [README](https://github.com/ansible-collections/cisco.ios#release-notes) and by extension the copy of the README on the Ansible Galaxy page for the collection and Automation Hub. The file is packaged with the collection and installed alongside it. I don't mean to seem glib, but where else would you have us publish it?

Now whether this document is adequate or not is another story. It is generated automatically from fragments submitted with each PR... if a documentation snippet is not present, the PR cannot merge. That said, we are human and don't always get things right. I can make a redoubled effort to enforce our [changelog fragment guidelines](https://docs.ansible.com/ansible/latest/community/development_process.html#changelog-fragment-entry-format) as I try to do whenever I see them lacking.
