### ISSUE TITLE
ACE remarks implemented out of order by ios_acls module

### ISSUE THREAD

**Issue by aggressiveHiker** [ansible-collections/cisco.ios#695]
##### SUMMARY

In IOS, when configuring ACL remarks, any remark commands sent to the device are tied to the ACE configured immediately after configuring the remarks. This provides the ability to comment on ACEs within longer ACLs giving any viewer of the ACL the ability to see what the purpose of each ACE is, similar to well-commented code.

When configuring remarks from the cisco.ios.ios_acls module, however, all remarks are sent to the end of the ACL instead of being tied to individual sequence numbers. As a result, the remarks only function as commentary for the entire ACL, rather than commentary for each individual ACE.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_acls
##### ANSIBLE VERSION

```paste below
ansible [core 2.13.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible_user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/network_automation/ansible-core-venv/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/ansible_user/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/network_automation/ansible-core-venv/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection Version
---------- -------
cisco.ios  4.0.0
```

##### CONFIGURATION

```paste below
No changes to ansible.cfg
```

##### OS / ENVIRONMENT

```
Switch Ports Model                     SW Version            SW Image
------ ----- -----                     ----------            ----------
*    1 16    WS-C3560CX-12PC-S         15.2(4)E8             C3560CX-UNIVERSALK9-M
```
##### STEPS TO REPRODUCE

Raw config commands in IOS:
```
conf t
ip access-list extended TEST
remark FIRST REMARK BEFORE LINE 10
remark ============
remark ALLOW HOST FROM BUILDING 10
10 permit ip host 1.1.1.1 any
remark FIRST REMARK BEFORE LINE 20
remark ============
remark ALLOW HOST FROM BUILDING 20
20 permit ip host 2.2.2.2 any
remark FIRST REMARK BEFORE LINE 30
remark ============
remark ALLOW NEW HOST FROM BUILDING 10
30 permit ip host 3.3.3.3 any
end
```
Playbook task intended to provide same commands:

```yaml
- name: Create or replace TEST ACL
  cisco.ios.ios_acls:
    config:
    - afi: ipv4
      acls:
      - name: TEST
        acl_type: extended
        aces:
        - sequence: 10
          remarks:
          - "FIRST REMARK BEFORE LINE 10"
          - "============"
          - "ALLOW HOST FROM BUILDING 10"
          grant: permit
          protocol: ip
          source:
            host: 1.1.1.1
          destination:
            any: true
        - sequence: 20
          remarks:
          - "FIRST REMARK BEFORE LINE 20"
          - "============"
          - "ALLOW HOST FROM BUILDING 20"
          grant: permit
          protocol: ip
          source:
            host: 2.2.2.2
          destination:
            any: true
        - sequence: 30
          remarks:
          - "FIRST REMARK BEFORE LINE 30"
          - "============"
          - "ALLOW NEW HOST FROM BUILDING 10"
          grant: permit
          protocol: ip
          source:
            host: 3.3.3.3
          destination:
            any: true
    state: replaced
```

##### EXPECTED RESULTS

In IOS, when configuring ACL remarks, any remark commands sent to the device are tied to the ACE configured immediately after configuring the remarks. In the steps to reproduce and expected output, there are three remarks tied to ACE sequence 10, three remarks tied to ACE sequence 20, and three remarks tied to ACE sequence 30. The playbook tasks are written in the same manner.

The output from running the task should be the same as the output from running the raw IOS config commands, ensuring idempotency.

Device output from running raw config commands in IOS:
```
Switch#show run | sec access-list
ip access-list extended TEST
 remark FIRST REMARK BEFORE LINE 10
 remark ============
 remark ALLOW HOST FROM BUILDING 10
 permit ip host 1.1.1.1 any
 remark FIRST REMARK BEFORE LINE 20
 remark ============
 remark ALLOW HOST FROM BUILDING 20
 permit ip host 2.2.2.2 any
 remark FIRST REMARK BEFORE LINE 30
 remark ============
 remark ALLOW NEW HOST FROM BUILDING 10
 permit ip host 3.3.3.3 any
Switch#

Switch#show access-list
Extended IP access list TEST
    10 permit ip host 1.1.1.1 any
    20 permit ip host 2.2.2.2 any
    30 permit ip host 3.3.3.3 any
Switch#
```
Expected "gathered" output from cisco.ios.ios_acls:
```
{
    "gathered": [
        {
            "afi": "ipv4",
            "acls": [
                {
                    "name": "TEST",
                    "acl_type": "extended",
                    "aces": [
                        {
                            "sequence": 10,
                            "remarks": [
                                "FIRST REMARK BEFORE LINE 10",
                                "============",
                                "ALLOW HOST FROM BUILDING 10"                               
                            ]
                            "grant": "permit",
                            "protocol": "ip",
                            "source": {
                                "host": "1.1.1.1"
                            },
                            "destination": {
                                "any": true
                            }
                        },
                        {
                            "sequence": 20,
                            "remarks": [
                                "FIRST REMARK BEFORE LINE 20",
                                "============",
                                "ALLOW HOST FROM BUILDING 20"                               
                            ]
                            "grant": "permit",
                            "protocol": "ip",
                            "source": {
                                "host": "2.2.2.2"
                            },
                            "destination": {
                                "any": true
                            }
                        },
                        {
                            "sequence": 30,
                            "remarks": [
                                "FIRST REMARK BEFORE LINE 30",
                                "============",
                                "ALLOW NEW HOST FROM BUILDING 10"                               
                            ]
                            "grant": "permit",
                            "protocol": "ip",
                            "source": {
                                "host": "3.3.3.3"
                            },
                            "destination": {
                                "any": true
                            }
                        },
                    ]
                },
            ]
        },
    ],
    "changed": false,
    "failed": false
}
```
##### ACTUAL RESULTS

When running the playbook task, instead of tying the remarks to the individual ACE sequence numbers, the ios_acls module moves all of the remarks to the end of the configuration and places them at the end of the ACL. Also, since there is a "duplicate" remark between the three ACEs, the duplicates are removed and only one iteration of it remains.

The end result is that the ACE exceptions for building 10, building 20, and new host from building 10 are completely indistinguishable from one another.

Device output from running playbook task:
```paste below
Switch#show run | sec access-list
ip access-list extended TEST
 permit ip host 1.1.1.1 any
 permit ip host 2.2.2.2 any
 permit ip host 3.3.3.3 any
 remark FIRST REMARK BEFORE LINE 10
 remark ============
 remark ALLOW HOST FROM BUILDING 10
 remark FIRST REMARK BEFORE LINE 20
 remark ALLOW HOST FROM BUILDING 20
 remark FIRST REMARK BEFORE LINE 30
 remark ALLOW NEW HOST FROM BUILDING 10
Switch#

Switch#show access-list
Extended IP access list TEST
    10 permit ip host 1.1.1.1 any
    20 permit ip host 2.2.2.2 any
    30 permit ip host 3.3.3.3 any
Switch#
```
Actual "gathered" output from cisco.ios.ios_acls:
```
{
    "gathered": [
        {
            "afi": "ipv4",
            "acls": [
                {
                    "name": "TEST",
                    "acl_type": "extended",
                    "aces": [
                        {
                            "sequence": 10,
                            "grant": "permit",
                            "protocol": "ip",
                            "source": {
                                "host": "1.1.1.1"
                            },
                            "destination": {
                                "any": true
                            }
                        },
                        {
                            "sequence": 20,
                            "grant": "permit",
                            "protocol": "ip",
                            "source": {
                                "host": "2.2.2.2"
                            },
                            "destination": {
                                "any": true
                            }
                        },
                        {
                            "sequence": 30,
                            "grant": "permit",
                            "protocol": "ip",
                            "source": {
                                "host": "3.3.3.3"
                            },
                            "destination": {
                                "any": true
                            }
                        },
                        {
                            "remarks": [
                                "FIRST REMARK BEFORE LINE 10",
                                "============",
                                "ALLOW HOST FROM BUILDING 10",
                                "FIRST REMARK BEFORE LINE 20",
                                "ALLOW HOST FROM BUILDING 20",
                                "FIRST REMARK BEFORE LINE 30",
                                "ALLOW NEW HOST FROM BUILDING 10"
                            ]
                        }
                    ]
                },
            ]
        },
    ],
    "changed": false,
    "failed": false
}
```

**Comment by aggressiveHiker** [comment]
Hey, @KB-perByte

Thanks so much for the response. I think I might have an idea on how to make this work with the limitations you identified, but I don't know the inner workings of the module code, so have to defer to your expertise on it.

In looking at this, I was trying to figure out exactly what's happening under the hood to gather the ACL details. I'm not sure how to look at the code itself and see what it's doing, but in ios_acls.py it states the following:

>The value of (running_config) option should be the same format as the output of commands (show access-list) and (show running-config | include ip(v6)* access-list|remark) executed on device.

My understanding of that statement is that the module will use those two commands when performing a gather operation to compare states for idempotency. The first command fired shows the numbered ACEs, but no remarks:

```
Switch#show access-list
Extended IP access list TEST
    10 permit ip host 1.1.1.1 any
    20 permit ip host 2.2.2.2 any
    30 permit ip host 3.3.3.3 any
Switch#
```
And then the second command fired shows the ACL names and remarks within the ACL, but no ACEs or relation between remarks and ACEs, because of the "include" operation:
```
Switch#show running-config | include ip(v6)* access-list|remark
ip access-list extended TEST
 remark FIRST REMARK BEFORE LINE 10
 remark ============
 remark ALLOW HOST FROM BUILDING 10
 remark FIRST REMARK BEFORE LINE 20
 remark ============
 remark ALLOW HOST FROM BUILDING 20
 remark FIRST REMARK BEFORE LINE 30
 remark ============
 remark ALLOW NEW HOST FROM BUILDING 10
Switch#
```
If, rather than using the "include" operation, we instead use the "section" operation, it now shows the full ACL as it is listed in the running-config, with all ordered relations between remarks and ACEs:
```
Switch#show running-config | section ip(v6)* access-list
ip access-list extended TEST
 remark FIRST REMARK BEFORE LINE 10
 remark ============
 remark ALLOW HOST FROM BUILDING 10
 permit ip host 1.1.1.1 any
 remark FIRST REMARK BEFORE LINE 20
 remark ============
 remark ALLOW HOST FROM BUILDING 20
 permit ip host 2.2.2.2 any
 remark FIRST REMARK BEFORE LINE 30
 remark ============
 remark ALLOW NEW HOST FROM BUILDING 10
 permit ip host 3.3.3.3 any
Switch#
```
The first command (show access-list) will always be required because it lists the sequence numbers for the ACEs. If the module were to use (show running-config | section ip(v6)* access-list) as the second command instead of what it currently uses, would it be possible to merge the unnumbered ACEs from the second command with the numbered ACEs from the first command, thereby establishing the relationship between ACEs and remarks?

**Comment by KB-perByte** [comment]
@aggressiveHiker Appreciate your efforts here. We have been over the idea you shared. And yes ` show running-config | section ip(v6)* access-list` using the following command will help us preserve the order when we read the data and convert it into structured data. But a sequence of problems starts when we are looking at action states where the user opts to change a set of configurations. 
So if we enable the user to add an index to the remarks commands that are to be fired the user cannot be sure or predict the set of commands that would be generated on the end of a play execution.
And if we try to preserve the order of commands that is already in the device. While pushing commands via overridden/replaced state post negation of a specific command we cannot be certain when the remarks command needs to be pushed (what relative order).
The appliance has remarks as an attribute that supports multiple entries and it's being creatively used to add information to each ace entries.
Regards

**Comment by aggressiveHiker** [comment]
@KB-perByte Thanks so much for the additional information on this. I'll see what I can work out using the ios_config module to get the remarks where I need them.

**Comment by KB-perByte** [comment]
@aggressiveHiker thanks again, we are actively looking out for such improvements.
Thanks for your input.

**Comment by aggressiveHiker** [comment]
@KB-perByte Thanks again for looking at this with me. I was reading over this again, and I'd like to address something you stated in your last substantial reply.

>@aggressiveHiker Appreciate your efforts here. We have been over the idea you shared. And yes `show running-config | section ip(v6)* access-list` using the following command will help us preserve the order when we read the data and convert it into structured data. But a sequence of problems starts when we are looking at action states where the user opts to change a set of configurations.
So if we enable the user to add an index to the remarks commands that are to be fired the user cannot be sure or predict the set of commands that would be generated on the end of a play execution.
And if we try to preserve the order of commands that is already in the device. While pushing commands via overridden/replaced state post negation of a specific command we cannot be certain when the remarks command needs to be pushed (what relative order).
The appliance has remarks as an attribute that supports multiple entries and it's being creatively used to add information to each ace entries.
Regards

From giving that a re-read, I think your primary concern with adding sequence numbering for remarks is the inability to predict what will happen in more complex configurations, especially when negating things. Is that correct?

I hope I'm not misstating here, but in looking at your final statment of *"The appliance has remarks as an attribute that supports multiple entries and it's being creatively used to add information to each ace entries."*, I believe your understanding of how remarks function in Cisco ACLs is incorrect. The remarks are not for the benefit of the ACL, but for the ACEs themselves.

When a remark is entered in an ACL, it is tied to the subsequent ACE configured and is then bound to that ACE "for life". If remarks are sent to the ACL with no subsequent ACE, they are simply staged for the next ACE that is configured, whenever that may be. At no point is a remark tied to the ACL itself. Additionally, duplicate remarks are allowed, but only when tied to separate ACEs. A single ACE is never allowed duplicate remarks.

Once configured, if an ACE is removed, the remarks that are tied to that ACE are removed along with it. If there are any "staged" remarks at the end of the ACL, those will remain until either a `no remark` command is issued, a new ACE is configured for those remarks to be tied to, or the ACL itself is removed.

The ios_acls module currently adds remarks to the end of an ACL, and as such, is leaving them staged for the next ACE entry added to the ACL.

Consider the original ACL example I used when opening this issue. We can see ACEs 10, 20, and 30, each with their corresponding remarks.
```
Switch#show access-list
Extended IP access list TEST
    10 permit ip host 1.1.1.1 any
    20 permit ip host 2.2.2.2 any
    30 permit ip host 3.3.3.3 any
Switch#
Switch#show running-config | section ip access-list
ip access-list extended TEST
 remark FIRST REMARK BEFORE LINE 10
 remark ============
 remark ALLOW HOST FROM BUILDING 10
 permit ip host 1.1.1.1 any
 remark FIRST REMARK BEFORE LINE 20
 remark ============
 remark ALLOW HOST FROM BUILDING 20
 permit ip host 2.2.2.2 any
 remark FIRST REMARK BEFORE LINE 30
 remark ============
 remark ALLOW NEW HOST FROM BUILDING 10
 permit ip host 3.3.3.3 any
Switch#
```

If we go back into the ACL and remove ACE 20, it will remove the remarks tied to that ACE.
```
Switch(config)#ip access-list extended TEST
Switch(config-ext-nacl)#no 20
Switch(config-ext-nacl)#end
```

```
Switch#show ip access-list
Extended IP access list TEST
    10 permit ip host 1.1.1.1 any
    30 permit ip host 3.3.3.3 any
Switch#show running-config | section ip access-list
ip access-list extended TEST
 remark FIRST REMARK BEFORE LINE 10
 remark ============
 remark ALLOW HOST FROM BUILDING 10
 permit ip host 1.1.1.1 any
 remark FIRST REMARK BEFORE LINE 30
 remark ============
 remark ALLOW NEW HOST FROM BUILDING 10
 permit ip host 3.3.3.3 any
Switch#
```

Now if we configure some "end-of-ACL" comments, we'll see them at the end of the ACL. Although they appear to be at the end of the ACL, they are only staged, awaiting an ACE to be associated with.
```
Switch(config)#ip access-list extended TEST
Switch(config-ext-nacl)#remark FIRST REMARK AT END OF ACL
Switch(config-ext-nacl)#remark SECOND REMARK AT END OF ACL
Switch(config-ext-nacl)#end
```

```
Switch#show ip access-list
Extended IP access list TEST
    10 permit ip host 1.1.1.1 any
    30 permit ip host 3.3.3.3 any
Switch#show running-config | section ip access-list
ip access-list extended TEST
 remark FIRST REMARK BEFORE LINE 10
 remark ============
 remark ALLOW HOST FROM BUILDING 10
 permit ip host 1.1.1.1 any
 remark FIRST REMARK BEFORE LINE 30
 remark ============
 remark ALLOW NEW HOST FROM BUILDING 10
 permit ip host 3.3.3.3 any
 remark FIRST REMARK AT END OF ACL
 remark SECOND REMARK AT END OF ACL
Switch#
```

If we go back into the ACL and configure a new ACE with sequence number 15, we'll see that these staged remarks become associated with the new ACE.
```
Switch(config)#ip access-list extended TEST
Switch(config-ext-nacl)#15 permit ip host 1.1.1.5 any
Switch(config-ext-nacl)#end
```

```
Switch#show ip access-list
Extended IP access list TEST
    10 permit ip host 1.1.1.1 any
    15 permit ip host 1.1.1.5 any
    30 permit ip host 3.3.3.3 any
Switch#show running-config | section ip access-list
ip access-list extended TEST
 remark FIRST REMARK BEFORE LINE 10
 remark ============
 remark ALLOW HOST FROM BUILDING 10
 permit ip host 1.1.1.1 any
 remark FIRST REMARK AT END OF ACL
 remark SECOND REMARK AT END OF ACL
 permit ip host 1.1.1.5 any
 remark FIRST REMARK BEFORE LINE 30
 remark ============
 remark ALLOW NEW HOST FROM BUILDING 10
 permit ip host 3.3.3.3 any
Switch#
```

Separately, we can quickly demonstrate that duplicate remarks are allowed, but only when attached to separate ACEs.
```
Switch(config)#ip access-list extended TEST
Switch(config-ext-nacl)#remark TEST REMARK
Switch(config-ext-nacl)#remark TEST REMARK
Duplicate remark statement
Switch(config-ext-nacl)#100 permit ip host 100.100.100.100 any
Switch(config-ext-nacl)#remark TEST REMARK
Switch(config-ext-nacl)#remark TEST REMARK
Duplicate remark statement
Switch(config-ext-nacl)#110 permit ip host 110.110.110.110 any
Switch(config-ext-nacl)#remark TEST REMARK
Switch(config-ext-nacl)#remark TEST REMARK
Duplicate remark statement
Switch(config-ext-nacl)#120 permit ip host 120.120.120.120 any
Switch(config-ext-nacl)#end
```

```
Switch#show ip access-list
Extended IP access list TEST
    10 permit ip host 1.1.1.1 any
    15 permit ip host 1.1.1.5 any
    30 permit ip host 3.3.3.3 any
    100 permit ip host 100.100.100.100 any
    110 permit ip host 110.110.110.110 any
    120 permit ip host 120.120.120.120 any
Switch#show running-config | section ip access-list
ip access-list extended TEST
 remark FIRST REMARK BEFORE LINE 10
 remark ============
 remark ALLOW HOST FROM BUILDING 10
 permit ip host 1.1.1.1 any
 remark FIRST REMARK AT END OF ACL
 remark SECOND REMARK AT END OF ACL
 permit ip host 1.1.1.5 any
 remark FIRST REMARK BEFORE LINE 30
 remark ============
 remark ALLOW NEW HOST FROM BUILDING 10
 permit ip host 3.3.3.3 any
 remark TEST REMARK
 permit ip host 100.100.100.100 any
 remark TEST REMARK
 permit ip host 110.110.110.110 any
 remark TEST REMARK
 permit ip host 120.120.120.120 any
Switch#
```

In summary, if the behavior of the ios_acls module were modified to fire remarks only when tied to ACEs, and when negating commands, only negate ACEs themselves, but never remarks, would that solve the issue?

There's also the question of breaking how people might currently be using the remarks option in the ios_acls module, so the existing functionality could be left in place in addition to adding the sequence numbers. Then a task could look something like this:

```
- name: Create or replace TEST ACL
  cisco.ios.ios_acls:
    config:
    - afi: ipv4
      acls:
      - name: TEST
        acl_type: extended
        aces:
        - sequence: 10
          remarks:
          - "FIRST REMARK BEFORE LINE 10"
          - "============"
          - "ALLOW HOST FROM BUILDING 10"
          grant: permit
          protocol: ip
          source:
            host: 1.1.1.1
          destination:
            any: true
        - sequence: 20
          remarks:
          - "FIRST REMARK BEFORE LINE 20"
          - "============"
          - "ALLOW HOST FROM BUILDING 20"
          grant: permit
          protocol: ip
          source:
            host: 2.2.2.2
          destination:
            any: true
        - sequence: 30
          remarks:
          - "FIRST REMARK BEFORE LINE 30"
          - "============"
          - "ALLOW NEW HOST FROM BUILDING 10"
          grant: permit
          protocol: ip
          source:
            host: 3.3.3.3
          destination:
            any: true
        - remarks:
          - "FIRST REMARK AT END OF ACL"
          - "SECOND REMARK AT END OF ACL"
    state: replaced
```
In that case, the first three blocks of remarks are tied to ACEs 10, 20, and 30, and then the last set is not tied to anything and is sent to the end of the ACL.

Thanks again for your time. I really appreciate you looking at this with me.

**Comment by KB-perByte** [comment]
@aggressiveHiker that was some quality explanation, I have observed the sticky behavior of remarks with ACLs and yes you do have a point from an end-user standpoint. And the placement of remarks attribute within the ace_s_ and an acl makes sense to me. But there are still some challenges to accommodate them with the action states we support.
Let me re-open this issue, and triage things to estimate the changes that can be added.
Thanks again.

**Comment by niekvlessert** [comment]
I've been reading this ticket with interest. We have a big number of ACLs on even more devices and I discovered this problem as well, it's making it impossible to use the ios.ios_acls for us. Of course I can implement it manually myself, but that's a lot of work and I do favor Python or PHP for doing it, we don't want that right? ;) So is there any progress on this? If I need to test anything or something, I'm available.

I agree with the explanation from aggresiveHiker, I guess that is what's missing in the implementation.
