### ISSUE TITLE
Add mode parameter to cisco.ios.ios_interfaces to manage the state of the interface

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.ios#701]
##### SUMMARY

Add mode parameter to cisco.ios.ios_interfaces to manage the state of the interface.

##### ISSUE TYPE
We have to rely on creating templates to run commands depending if the interface is layer 2 or 3.

##### COMPONENT NAME

cisco.ios.ios_interfaces

##### ADDITIONAL INFORMATION

    - name: Update l3_interfaces
      cisco.ios.ios_interfaces:
      config:
      - name: Vlan51
        mode: layer3
      state: merged

    - name: Update l2_interfaces
      cisco.ios.ios_interfaces:
      config:
      - name: Vlan51
        mode: layer2
      state: merged

**Comment by bentole** [comment]
Hi @digitalfiend64 ! I'm a bit curious about this one. I guess you can test whether interfaces are layer 2 or layer 3 by using facts and other things. I notice in your play that SVIs are used. Arent' they by definition layer 3? Or are they used as examples only? Could you elaborate more on the intent here? Sorry if any of this is obvious. I'm not the person who paid most attention in class 😊

**Comment by digitalfiend64** [comment]
> Hi @digitalfiend64 ! I'm a bit curious about this one. I guess you can test whether interfaces are layer 2 or layer 3 by using facts and other things. I notice in your play that SVIs are used. Arent' they by definition layer 3? Or are they used as examples only? Could you elaborate more on the intent here? Sorry if any of this is obvious. I'm not the person who paid most attention in class blush

Hi Bentole,
  I'll followup with my customer as I opened this on their behalf and followup with you as soon as I hear back.

**Comment by digitalfiend64** [comment]
Here's the response back from my customer, please let me know what else you need:

The SVIs that are in the original document are just examples. The idea behind having 'mode' under cisco.ios.ios_interfaces is that with a mode parameter, we wouldn't need to use a task and template just to run  'switchport', 'no switchport', or 'no switchport mode' (iosxe)

**Comment by KB-perByte** [comment]
Hey @digitalfiend64 so _switchport_ being an attribute of l2_interfaces module can be configured or negated via the ios_l2_interfaces module only. It will not be correct in terms of resource module to use ios_interfaces to configure or deal with switchport configuration.
It is always recommended to have specific tasks at the module level. Which makes doing configuration specific to that resource much simple and clean.
Regards

**Comment by KB-perByte** [comment]
tagging similar issue here : https://github.com/ansible-collections/cisco.ios/issues/737
