### ISSUE TITLE
The cisco.ios.ios_l3_interfaces module doesn’t add a ipv4 address to a Cisco 4948 device

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.ios#702]
##### SUMMARY

The cisco.ios.ios_l3_interfaces module doesn’t add a ipv4 address to a Cisco 4948 device.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module name: cisco.ios.ios_l3_interfaces

##### ANSIBLE VERSION

Ansible v2.9.27

##### COLLECTION VERSION

# /usr/local/lib/python3.8/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.8.1  

# /home/<username>/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  4.0.0

##### CONFIGURATION

DEFAULT_LOAD_CALLBACK_PLUGINS(/home/<username>/.ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/<username>/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/<username>/.ansible.cfg) = 120
DEPRECATION_WARNINGS(/home/<username>/.ansible.cfg) = False
GALAXY_IGNORE_CERTS(/home/<username>/.ansible.cfg) = True
GALAXY_SERVER_LIST(/home/<username>/.ansible.cfg) = ['inbound_yeti_repo', 'published_repo', 'rh-certified_repo']
HOST_KEY_CHECKING(/home/<username>/.ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/home/<username>/.ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/home/<username>/.ansible.cfg) = 300
PERSISTENT_CONNECT_TIMEOUT(/home/<username>/.ansible.cfg) = 120
RETRY_FILES_ENABLED(/home/<username>/.ansible.cfg) = False

##### OS / ENVIRONMENT

Cisco IOS Software, Catalyst 4500 L3 Switch  Software (cat4500e-ENTSERVICESK9-M), Version 15.2(4)E2, RELEASE SOFTWARE (fc2)

##### STEPS TO REPRODUCE

1. Run the Update l3_interaces task

    - name: Update l3_interfaces
      cisco.ios.ios_l3_interfaces:
      config:
      - name: Vlan51
        Ipv4:
        - address: 192.168.1.3/31
      state: merged

##### EXPECTED RESULTS

Step #1 should add an ipv4 address to the interface.

##### ACTUAL RESULTS

fatal: [4948E-02]: FAILED! => changed=false 
  invocation:
    module_args:
      config:
      - ipv4:
        - address: 192.168.1.3/31
          dhcp: null
          dhcp_client: null
          dhcp_hostname: null
          pool: null
          secondary: null
        ipv6: null
        name: Vlan50
      running_config: null
      state: merged
  msg: address format is <ipv6 address>/<mask>, got invalid format dhcp

**Comment by KB-perByte** [comment]
Hey @digitalfiend64 can you please update the collection version to the latest and give it a try?
The collection version I see here I quite old.
Regards

**Comment by digitalfiend64** [comment]
Same issue replicated with cisco.ios v4.2.0.  Is there a newer version that should be tried.

**Comment by digitalfiend64** [comment]
Dear maintainer, I see this was fixed in merge #700 but I do not see this issue or merge #700 in the latest *changelog. 
 What collection version should this be resolved in?
 
*) Changelog Referenced: https://github.com/ansible-collections/cisco.ios/blob/main/changelogs/changelog.yaml
