### ISSUE TITLE
ios_facts:Integration test issue:assertion failed

### ISSUE THREAD

**Issue by komaldesai13** [ansible-collections/cisco.ios#825]
##### SUMMARY
When running ios_facts integration tests from Controller with EE container,
We get an unexpected error: Assertion failed
On task [Collect list of available network resources for IOS](https://github.com/ansible-collections/cisco.ios/blob/main/tests/integration/targets/ios_facts/tests/cli/all_facts.yaml#L51)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
iOS_facts

##### ANSIBLE VERSION
2.14

##### COLLECTION VERSION

17.6.2
##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE
Run integration iosxr_banner test, the following task failed.
See below the actual results.

##### EXPECTED RESULTS
The task will pass with not errors.

##### ACTUAL RESULTS

TASK [/usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_facts : Collect list of available network resources for IOS] ***
task path: /usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_facts/tests/cli/all_facts.yaml:51
redirecting (type: action) cisco.ios.ios_facts to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_facts to cisco.ios.ios
ok: [10.0.205.140] => {
    "ansible_facts": {
        "ansible_net_api": "cliconf",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_hostname": "foo",
        "ansible_net_image": "bootflash:packages.conf",
        "ansible_net_iostype": "IOS-XE",
        "ansible_net_model": "C8000V",
        "ansible_net_operatingmode": "autonomous",
        "ansible_net_python_version": "3.9.13",
        "ansible_net_serialnum": "93WF9G05F7U",
        "ansible_net_system": "ios",
        "ansible_net_version": "17.06.02",
        "ansible_network_resources": {},
        "available_network_resources": [
            "acl_interfaces",
            "acls",
            "bgp_address_family",
            "bgp_global",
            "hostname",
            "interfaces",
            "l2_interfaces",
            "l3_interfaces",
            "lacp",
            "lacp_interfaces",
            "lag_interfaces",
            "lldp_global",
            "lldp_interfaces",
            "logging_global",
            "ntp_global",
            "ospf_interfaces",
            "ospfv2",
            "ospfv3",
            "prefix_lists",
            "route_maps",
            "service",
            "snmp_server",
            "static_routes",
            "vlans"
        ]
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "available_network_resources": true,
            "gather_network_resources": null,
            "gather_subset": [
                "min"
            ]
        }
    }
}

TASK [/usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_facts : Assert that correct available_network_resources returned] ***
task path: /usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_facts/tests/cli/all_facts.yaml:56
fatal: [10.0.205.140]: FAILED! => {
    "assertion": false,
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}

**Comment by KB-perByte** [comment]
@komaldesai13 we got a contribution for a new module, I would fix it shortly. 
Thanks for notifying me.

**Comment by komaldesai13** [comment]
Thank you :-)
