### ISSUE TITLE
Before values are empty on WS-C4500X-32

### ISSUE THREAD

**Issue by sachinsprasad** [ansible-collections/cisco.ios#890]
Yes
 Yes

##### SUMMARY
I am writing a playbook to audit NTP Config. 
On a WS-C4510R+E running code 03.11.04.E, I am getting before values -
"before": {
        "servers": [
            {
                "server": "10.113.15.158"
            },
            {
                "prefer": true,
                "server": "10.113.60.176"

On a 'WS-C4500X-32' running code 03.11.04.E, I don't get any before values even though NTP is configured 
before": {},

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_ntp_global module

##### ANSIBLE VERSION

```


```

##### COLLECTION VERSION

```
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nzt-ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/nzt-ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

##### CONFIGURATION

```
CONFIG_FILE() = /etc/ansible/ansible.cfg
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

WS-C4500X-32  running code 03.11.04.E
System image file is "bootflash:cat4500e-universalk9.SPA.03.11.04.E.152-7.E4.bin"

##### STEPS TO REPRODUCE

Use NTP Module to configure ntp on WS-C4500X-32. NTP must already be configured. Run the command with -vvv

```
 ansible-playbook 01-ntp-compliance.yml --check  -vvv

```

##### EXPECTED RESULTS

Return configured NTP values

##### ACTUAL RESULTS

Does not return any configured NTP servers 

```
changed: [s01.net.ts.com] => {
    "after": {},
    "before": {},
    "changed": true,
    "commands": [
        "ntp server 10.188.26.119",
        "ntp server 10.128.152.81"

```

**Comment by KB-perByte** [comment]
Hello @sachinsprasad The facts are not generated as the collection does not get the desired configuration from the appliance. Note -  IOSXE 17.x is the latest supported IOSXE version and as per this [documentation](https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst4500/release/note/ol-311xe-4500x.html) from Cisco. The version reported is not supported anymore.
Could you please share the output of `show running-config | section ^ntp` command for me to verify the configuration?
Regards

**Comment by sachinsprasad** [comment]
Interesting --
I ran the command and it didn't return any ntp servers, although I know ntp is configured.

sjo02-sw-core01#sh running-config | section ^ntp
sjo02-sw-core01#

Looking at the config. it looks like when you configure ntp, it puts the command under module provision

module provision switch 2
 chassis-type 72 base-mac 5C71.0DE3.4380
 slot 1 slot-type 402 base-mac 5C71.0DE3.4380
 slot 2 slot-type 400 base-mac 2C4F.5222.5628
 
!

 ntp source Vlan90
 ntp server 10.113.60.170
 ntp server 10.113.15.150

**Comment by KB-perByte** [comment]
Yes, that is the case. The appliance doesn't generate any output for the module to generate facts aka before/after
Well, I disagree with the second part it is not enforcing it to be under module provision as it is separated by a "!" 

Could you share the output for  `sh running-config | ? ` trying to check if `section` is supported properly or not? 
Closing the issue as this would be a not fix.
Regards.

**Comment by sachinsprasad** [comment]
looks like section is supported.. For some reason there is a space in front of ntp config 

sjo02-sw-core01#sh running-config | ?
  append    Append redirected output to URL (URLs supporting append operation only)
  begin     Begin with the line that matches
  count     Count number of lines which match regexp
  exclude   Exclude lines that match
  format    Format the output using the specified spec file
  include   Include lines that match
  redirect  Redirect output to URL
  section   Filter a section of output
  tee       Copy output to URL

sjo02-sw-core01#sh running-config | section ntp
 ntp source Vlan90
 ntp server 10.113.60.176
 ntp server 10.113.15.158

sjo02-sw-core01#sh running-config | section ^ntp
sjo02-sw-core01#
