### ISSUE TITLE
[cli_command]ShuttingDown/BringingUP BGP peer

### ISSUE THREAD

**Issue by yananthan** [ansible-collections/cisco.ios#927]
HI Team,
I have written setof playbooks to shutting down / bringing up BGP peer using ansible.
When I using for the testing, I am having weired situation like as follwos.
-> When I run shutting down the BGP peer playbook, it will shutting down peers as expected
-> When I run bringing UP BGP peer playbook, it will bringing up only partial configuration. So I need to run second time to bring UP all the BGP peers

I have atatched the necessary documents for your reference.
-> bgpconfig : BGP configuration in the router
-> shuttingbgpfromcli.yml : shutting BGP peer playbook
-> aftershutgetbgpinfo: BGP Information after run the shutting down BGP peer playbook
-> bgpconfigaftershut: BGP configuration after shutdown
-> bringupbgpfromcli.yml: bringing up BGP peer playbook
-> bringingupbgp1 : Run the bring up BGP peer playbook first time
-> afterbringupgetbgpinfo1 : BGP Information after first time run the bring up BGP peer playbook
-> bgpconfigafterbringup1: BGP configuration after first time run the bring up BGP peer playbook 
-> bringingupbgp2 : Run teh bring up BGP peer playbook second time
-> afterbringupgetbgpinfo2 : BGP Information after second time run the bring up BGP peer playbook
-> bgpconfigafterbringup2: BGP configuration after second time run the bring up BGP peer playbook 
{https://github.com/yananthan/ansiblebgp/tree/main} 

Please advise me where I stuck..

Thanks..

**Comment by KB-perByte** [comment]
Hey @yananthan we don't validate or guide the usage of any of our modules, please look at the documentation of the existing resource modules for more information. 
Ref : [bgp_global](https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_bgp_global_module.html), [bgp_address_family](https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_bgp_address_family_module.html#ansible-collections-cisco-ios-ios-bgp-address-family-module)
Regards

**Comment by yananthan** [comment]
> Hey @yananthan we don't validate or guide the usage of any of our modules, please look at the documentation of the existing resource modules for more information. Ref : [bgp_global](https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_bgp_global_module.html), [bgp_address_family](https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_bgp_address_family_module.html#ansible-collections-cisco-ios-ios-bgp-address-family-module) Regards

Hi KB,
cli_command module is a ansible native command. The purpose I posted here is for Cisco experts to get touch.
Thank you.
