### ISSUE TITLE
Ansible (cisco.ios.ios_facts) does not support the use of BGP AS numbers in dot format.

### ISSUE THREAD

**Issue by nimaazizibabani** [ansible-collections/cisco.ios#932]
##### SUMMARY

I attempted to utilize network fact against an iOS device that possesses BGP AS number with dot format. This is the BGP command on the router (router bgp 10.64760). I got the below error

fatal: [xxx]: FAILED! => changed=false 
  msg: 'argument ''remote_as'' is of type <class ''float''> found in ''config -> address_family -> neighbors''. and we were unable to convert to int: <class ''float''> cannot be converted to an int'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

 cisco.ios.ios_facts
##### ANSIBLE VERSION

```paste below
ansible [core 2.14.0]
python version = 3.10.6
```

##### COLLECTION VERSION

```paste below
cisco.ios                     3.2.0 
```

##### CONFIGURATION

```paste below
 tasks:
    - name: Find the AS number
      cisco.ios.ios_facts:
        gather_subset:
          - "!all"
        gather_network_resources:
          - bgp_global
          - bgp_address_family
          - prefix_lists
          - route_maps
```

##### OS / ENVIRONMENT

mac
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by KB-perByte** [comment]
Hello @nimaazizibabani the issue was fixed way back as I recollect. Could you please update the collection version to the latest and give it a try. And also please consider sharing the configuration for the issue, for us to narrow it down.
Regards.

**Comment by nimaazizibabani** [comment]
Thanks @KB-perByte ,
the problem is related to bgp_address_family module and remote_as 

msg: 'argument ''remote_as'' is of type <class ''float''> found in ''config -> address_family -> neighbors''. and we were unable to convert to int: <class ''float''> cannot be converted to an int'
