### ISSUE TITLE
Leading white space on some IOS config lines

### ISSUE THREAD

**Issue by aoforb** [ansible-collections/cisco.ios#936]
##### SUMMARY
Leading white space in show running-config & show startup-config causes the ios_config module to fail diff checks when using the intended_config option. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_config

##### ANSIBLE VERSION
Versions tested
```
ansible core 2.13.7 / Python 3.8.10
ansible core 2.14.5 / Python 3.10.12
```

##### COLLECTION VERSION
```
# /opt/venv/ansible/lib/python3.10/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  4.5.0 
```

##### OS / ENVIRONMENT
Ansible is running on Linux 5.15.0-75-generic Ubuntu 22.04 

Target device
Cisco IOS Software [Fuji], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 16.8.1a, RELEASE SOFTWARE (fc1)

##### STEPS TO REPRODUCE
Retrieve the running configuration from a Cisco 9300 switch (or generate one using Jinja templates) and save it as "master.cfg." Afterward, execute the following task.

```yaml
- name: Check the running-config against master config
  cisco.ios.ios_config:
    diff_against: intended
    intended_config: "{{ lookup('file', 'master.cfg') }}"
  diff: true
```

The task will show many diff's because the configuration collected from the device has trailing white space on various commands.

Here is a comparison using notepad++
![image](https://github.com/ansible-collections/cisco.ios/assets/146780854/973b0d86-0218-49c4-96a7-82d1fee412d3)

##### EXPECTED RESULTS
Should be no diff reported

##### ACTUAL RESULTS
From the diff output.
![image](https://github.com/ansible-collections/cisco.ios/assets/146780854/df4090da-5adf-495a-a56e-db60a857fc13)

I believe a potential solution to the issue might involve removing trailing whitespace from the end of each configuration line obtained from the device. However, I'm uncertain whether this problem pertains to Cisco IOS or NetCommon.

Within NetCommon, the specific class in question is NetworkConfig(), and it appears that the issue may be addressed either within the NetworkConfig.load() function itself or by handling it before the function that invokes NetworkConfig.load().

**Comment by roverflow** [comment]
Hey @aoforb im not able to reproduce it on my end,maybe it is only happening with specific lines of config, could you provide me with a play that would give me similar config so i can try to reproduce it on my end

**Comment by aoforb** [comment]
Hello @roverflow, I appreciate your attention to this issue.

If you TFTP the running configuration from the switch and examine the file, you will notice that some lines of configuration end with trailing white spaces. It's important to ensure that your text editor does not remove these spaces when saving the file. The presence of these spaces seems random and doesn't follow a specific pattern. For instance, the configuration lines for VLANs are generally correct, except for VLAN 60.

![image](https://github.com/ansible-collections/cisco.ios/assets/146780854/1aa61250-a393-40ee-814c-4e01da4930ec)

The AAA configuration I shared earlier also contains these trailing spaces. This issue affects various parts of the configuration, including class maps, EIGRP routing, route maps, and SNMP configuration.

If you compare the configuration that was TFTP'd from the device with the intended configuration, you will find no differences. This is because both configurations have identical trailing whitespace.

However, when generating the intended configuration using Jinja templates, the task reveals differences because my Jinja template doesn't produce the same whitespace. I would be impossible to reproduce the white space anyway in the jinja template given how random it is.

The playbook is simple its just the one task I shared earlier, you'll just need to save the TFTP config as master.cfg and make sure it reachable by the task.

**Comment by aoforb** [comment]
Here's another affected line. I'm unsure if this issue would occur if executing this command on a blank switch or if the presence of other configurations in the file causes this to happen. It appears to be occurring randomly.

![image](https://github.com/ansible-collections/cisco.ios/assets/146780854/848799c1-1a35-4318-b64a-0d5e9a5c86f3)

**Comment by aoforb** [comment]
Hello @roverflow, how are you getting on with a fix?

**Comment by roverflow** [comment]
Hello @aoforb, I'm sorry for the delayed response. I couldn't reproduce the issue on my end. I suggest an alternative solution: you can iterate through the output, remove any whitespace, and then compare it. I hope this suggestion proves helpful.

**Comment by aoforb** [comment]
The output cannot be iterated through as the comparison is done within the module. What you're suggesting is create a custom built module to carryout the check which ultimately makes the module below redundant and should be removed from the collection.

python```
- name: Check the running-config against master config
  cisco.ios.ios_config:
    diff_against: intended
    intended_config: "{{ lookup('file', 'master.cfg') }}"
  diff: true
```
I'm going to carryout some further testing because the leading white space might affect other modules with idempotent checks.

Shame about the result, but thank you for taking the time to look into the bug.

**Comment by roverflow** [comment]
Hello @aoforb, Thankyou for you update, the issue you're encountering is related to the behavior of the Cisco device itself, and unfortunately, it falls outside the scope of enhancements we can make to the module.

While we strive to improve our modules, certain device-specific behaviors may limit the extent to which we can address certain issues. If you have any further questions or if there's anything else we can assist you with, please don't hesitate to reach out.

As for the solution you can run these set of tasks:
```  
  - name: Get running-config
    cisco.ios.ios_command:
      commands:
        - show running-config
    register: running_config_output

  - name: Replace whitespaces with \n
    set_fact:
      modified_lines: "{{ running_config_output.stdout_lines[0] | map('regex_replace', '[ ]$') | join('\n')}}"

  - name: Display modified lines
    ansible.builtin.debug:
      var: modified_lines
```
