### ISSUE TITLE
cisco.ios.ios_vlans  state: gathered not working

### ISSUE THREAD

**Issue by wddossett** [ansible-collections/cisco.ios#94]
##### SUMMARY

running playbook:

```
  - name: Gather listed vlans with provided configurations
    ios_vlans:
      config:
      state: gathered

produces error message:

`{
    "msg": "value of state must be one of: merged, replaced, overridden, deleted, got: gathered",
    "invocation": {
        "module_args": {
            "config": null,
            "state": "gathered"
        }
    },
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "_ansible_no_log": false,
    "changed": false
}`

```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_vlans
##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

```

##### CONFIGURATION

```paste below
[root@AWX ~]# ansible-config dump --only-changed
[root@AWX ~]# 

```

##### OS / ENVIRONMENT

terrapin-2960-bu#show version
Cisco IOS Software, C2960S Software (C2960S-UNIVERSALK9-M), Version 15.0(2a)SE9, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2015 by Cisco Systems, Inc.
Compiled Mon 21-Dec-15 02:41 by prod_rel_team

ROM: Bootstrap program is C2960S board boot loader
BOOTLDR: C2960S Boot Loader (C2960S-HBOOT-M) Version 12.2(55r)SE, RELEASE SOFTWARE (fc1)

##### STEPS TO REPRODUCE

run playbook against device

```yaml
---
- name: VLANS

  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  tasks:
  - name: Gather listed vlans with provided configurations
    ios_vlans:
      config:
      state: gathered


```

##### EXPECTED RESULTS

json output of all vlans

##### ACTUAL RESULTS

{
    "msg": "value of state must be one of: merged, replaced, overridden, deleted, got: gathered",
    "invocation": {
        "module_args": {
            "config": null,
            "state": "gathered"
        }
    },
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "_ansible_no_log": false,
    "changed": false
}

```
running this from AWX.  Launch with inventory and credential

```

**Comment by justjais** [comment]
@wddossett ios_vlans when got released in `2.9` supported only `merged, replaced, overridden and deleted` state and the newly introduced state `gathered, parsed and rendered` was merged in ios collection with PR: https://github.com/ansible-collections/cisco.ios/pull/41.

So, plz check and verify the same with the Cisco IOS collection. Thus, closing the issue
