### ISSUE TITLE
The size parameter of the ios_ping module does not work (collection cisco.ios 5.0.0)

### ISSUE THREAD

**Issue by Vovilla** [ansible-collections/cisco.ios#943]
The size parameter is in the doc for the module, but it is not processed in the module code.
The problem is that this parameter is not specified in the module argument specification PingArgs.argument_spec (/usr/share/ansible/collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/argspec/ping/ping.py)

class PingArgs(object):
    """The arg spec for the ios_ping module"""

    argument_spec = {
        "count": {"type": "int"},
        "afi": {"choices": ["ip", "ipv6"], "default": "ip", "type": "str"},
        "dest": {"required": True, "type": "str"},
        "df_bit": {"default": False, "type": "bool"},
        "source": {"type": "str"},
        "ingress": {"type": "str"},
        "egress": {"type": "str"},
        "timeout": {"type": "int"},
        "state": {"choices": ["absent", "present"], "default": "present", "type": "str"},
        "size": {"type": "int"}, # is missing
        "vrf": {"type": "str"},
    }

and the command template PingTemplate.PARSERS (/usr/share/ansible/collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/rm_templates/ping.py), which is sent to the device

class PingTemplate(NetworkTemplate):
    def __init__(self, lines=None):
        super(PingTemplate, self).__init__(lines=lines, tmplt=self)

    # fmt: off
    PARSERS = [
        {
            ....................
            "setval": "ping"
            "{{ (' vrf ' + vrf) if vrf is defined else '' }}"
            "{{ (' ' + afi|string ) if afi is defined else '' }}"
            "{{ (' ' + dest ) if dest is defined else '' }}"
            "{{ (' repeat ' + count|string ) if count is defined else '' }}"
            "{{ (' df-bit' ) if df_bit|d(False) else '' }}"
            "{{ (' timeout ' + timeout|string) if timeout is defined else '' }}"
            "{{ (' ingress ' + ingress) if ingress is defined else '' }}"
            "{{ (' egress ' + egress) if egress is defined else '' }}"
            "{{ (' source ' + source) if source is defined else '' }}"
             "{{ (' size ' + size|string ) if size is defined else '' }}", # is missing
            ....................
            },
        },
    ]

**Comment by PcInfamy** [comment]
@Vovilla did this get tracked somewhere else? I also noticed this issue

**Comment by roverflow** [comment]
> @Vovilla did this get tracked somewhere else? I also noticed this issue

@PcInfamy This issue has been resolved in one of the latest pr merge.

**Comment by PcInfamy** [comment]
@Vovilla ah I found the PR, thanks for fixing that. Any idea on next release date?
