### ISSUE TITLE
cisco.ios.ios_snmp - if_index: true, breakes idempotency:

### ISSUE THREAD

**Issue by jorgenspange** [ansible-collections/cisco.ios#947]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by KB-perByte** [comment]
closing this as there is a fresh issue https://github.com/ansible-collections/cisco.ios/issues/948 
Regards

**Comment by jorgenspange** [comment]
@KB-perByte I'm sorry, something wrong must have happened.
