### ISSUE TITLE
ios_config : Integration test issue:syntax issue

### ISSUE THREAD

**Issue by komaldesai13** [ansible-collections/cisco.ios#955]
##### SUMMARY
When running ios_config integration tests from Controller with EE container,
We get an unexpected error
On task [Run test cases ](https://github.com/ansible-collections/cisco.ios/blob/main/tests/integration/targets/ios_config/tests/cli/replace_config.yaml#L4)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION
2.14

##### COLLECTION VERSION
17.06.02

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE
Run integration ios_config test, the following task failed.
See below the actual results.

##### EXPECTED RESULTS
The task will pass with not errors.

##### ACTUAL RESULTS
TASK [/usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config : Run test cases (connection=ansible.netcommon.network_cli)] ***
task path: /usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config/tasks/cli.yaml:13
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
included: /usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config/tests/cli/backup.yaml for 10.0.205.140 => (item=/usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config/tests/cli/backup.yaml)
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
redirecting (type: modules) ansible.builtin.ios_config to cisco.ios.ios_config
included: /usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config/tests/cli/defaults.yaml for 10.0.205.140 => (item=/usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config/tests/cli/defaults.yaml)
redirecting (type: action) cisco.ios.ios_system to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
included: /usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config/tests/cli/diff.yaml for 10.0.205.140 => (item=/usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config/tests/cli/diff.yaml)
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_config to cisco.ios.ios
included: /usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config/tests/cli/macro.yaml for 10.0.205.140 => (item=/usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config/tests/cli/macro.yaml)
ERROR! couldn't resolve module/action 'cisco.nxos.nxos_config'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/usr/share/ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_config/tests/cli/replace_config.yaml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: "setup"
  ^ here

**Comment by NilashishC** [comment]
@komaldesai13 Closing this since it has been fixed now.
