### ISSUE TITLE
Issue with ios_acls (cisco.ios 5.2.0)

### ISSUE THREAD

**Issue by JeromeH27** [ansible-collections/cisco.ios#969]
##### SUMMARY

I'm trying to retrieve defined ACL on a switch with this task:

    - name: Collect ACL in JSON style
      cisco.ios.ios_acls:
        config:
        state: gathered
      register: CURRENT_ALL_ACL

with version 5.2.0, the return is not complete, there are missing the IP addresses defined in ACL. But with previous version it is working properly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_acls

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.13 (main, Oct 20 2022, 10:18:33) [GCC 8.5.0 20210514 (Red Hat 8.5.0-4)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection        Version
----------------- -------
ansible.netcommon 5.2.0
ansible.utils     2.11.0
cisco.ios         5.2.0

```

##### CONFIGURATION

```paste below
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco Model: WS-C2960X-48TD-L
IOS Version: 15.2(7)E7

##### STEPS TO REPRODUCE

```yaml
    - name: Collect ACL in JSON style
      cisco.ios.ios_acls:
        config:
        state: gathered
      register: CURRENT_ALL_ACL
```

##### ACTUAL RESULTS

```paste below

```

**Comment by KB-perByte** [comment]
@JeromeH27 can you share the output of `running-config | section access-list` for us narrow it down.
Regards.

**Comment by JeromeH27** [comment]
here the output
![ACL](https://github.com/ansible-collections/cisco.ios/assets/58164388/517d1ba6-5de5-4b7b-bb04-28e782afa168)
